endpoints.shutdown.enabled: true
endpoints.shutdown.sensitive: false

server:
  port: 8761

eureka:
  instance:
    hostname: 192.168.0.138
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/