package com.rs.ocp.domain.mappers;

import com.rs.ocp.domain.endity.AccAccpwd;
import com.rs.ocp.domain.endity.AccAccpwdExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface AccAccpwdMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table acc_accpwd
     *
     * @mbggenerated
     */
    int countByExample(AccAccpwdExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table acc_accpwd
     *
     * @mbggenerated
     */
    int deleteByExample(AccAccpwdExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table acc_accpwd
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer accpwdId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table acc_accpwd
     *
     * @mbggenerated
     */
    int insert(AccAccpwd record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table acc_accpwd
     *
     * @mbggenerated
     */
    int insertSelective(AccAccpwd record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table acc_accpwd
     *
     * @mbggenerated
     */
    List<AccAccpwd> selectByExample(AccAccpwdExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table acc_accpwd
     *
     * @mbggenerated
     */
    AccAccpwd selectByPrimaryKey(Integer accpwdId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table acc_accpwd
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") AccAccpwd record, @Param("example") AccAccpwdExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table acc_accpwd
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") AccAccpwd record, @Param("example") AccAccpwdExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table acc_accpwd
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(AccAccpwd record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table acc_accpwd
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(AccAccpwd record);
}