package com.rs.ocp.domain.mappers;

import com.rs.ocp.domain.endity.GameArea;
import com.rs.ocp.domain.endity.GameAreaExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface GameAreaMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table game_area
     *
     * @mbggenerated
     */
    int countByExample(GameAreaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table game_area
     *
     * @mbggenerated
     */
    int deleteByExample(GameAreaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table game_area
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer areaId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table game_area
     *
     * @mbggenerated
     */
    int insert(GameArea record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table game_area
     *
     * @mbggenerated
     */
    int insertSelective(GameArea record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table game_area
     *
     * @mbggenerated
     */
    List<GameArea> selectByExample(GameAreaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table game_area
     *
     * @mbggenerated
     */
    GameArea selectByPrimaryKey(Integer areaId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table game_area
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") GameArea record, @Param("example") GameAreaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table game_area
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") GameArea record, @Param("example") GameAreaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table game_area
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(GameArea record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table game_area
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(GameArea record);
}