package com.rs.ocp.domain.mappers;

import com.rs.ocp.domain.endity.GameLogin;
import com.rs.ocp.domain.endity.GameLoginExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface GameLoginMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table game_login
     *
     * @mbggenerated
     */
    int countByExample(GameLoginExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table game_login
     *
     * @mbggenerated
     */
    int deleteByExample(GameLoginExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table game_login
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer loginId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table game_login
     *
     * @mbggenerated
     */
    int insert(GameLogin record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table game_login
     *
     * @mbggenerated
     */
    int insertSelective(GameLogin record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table game_login
     *
     * @mbggenerated
     */
    List<GameLogin> selectByExample(GameLoginExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table game_login
     *
     * @mbggenerated
     */
    GameLogin selectByPrimaryKey(Integer loginId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table game_login
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") GameLogin record, @Param("example") GameLoginExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table game_login
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") GameLogin record, @Param("example") GameLoginExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table game_login
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(GameLogin record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table game_login
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(GameLogin record);
}