package com.rs.ocp.domain.mappers;

import com.rs.ocp.domain.endity.GameServer;
import com.rs.ocp.domain.endity.GameServerExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface GameServerMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table game_server
     *
     * @mbggenerated
     */
    int countByExample(GameServerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table game_server
     *
     * @mbggenerated
     */
    int deleteByExample(GameServerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table game_server
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer serverId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table game_server
     *
     * @mbggenerated
     */
    int insert(GameServer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table game_server
     *
     * @mbggenerated
     */
    int insertSelective(GameServer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table game_server
     *
     * @mbggenerated
     */
    List<GameServer> selectByExample(GameServerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table game_server
     *
     * @mbggenerated
     */
    GameServer selectByPrimaryKey(Integer serverId);
    
    
    GameServer selectByPrimaryKeyLimit1(Integer serverId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table game_server
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") GameServer record, @Param("example") GameServerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table game_server
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") GameServer record, @Param("example") GameServerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table game_server
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(GameServer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table game_server
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(GameServer record);
}