package com.rs.ocp.domain.mappers;

import com.rs.ocp.domain.endity.PpMbcard;
import com.rs.ocp.domain.endity.PpMbcardExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface PpMbcardMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pp_mbcard
     *
     * @mbggenerated
     */
    int countByExample(PpMbcardExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pp_mbcard
     *
     * @mbggenerated
     */
    int deleteByExample(PpMbcardExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pp_mbcard
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer mbcardId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pp_mbcard
     *
     * @mbggenerated
     */
    int insert(PpMbcard record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pp_mbcard
     *
     * @mbggenerated
     */
    int insertSelective(PpMbcard record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pp_mbcard
     *
     * @mbggenerated
     */
    List<PpMbcard> selectByExample(PpMbcardExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pp_mbcard
     *
     * @mbggenerated
     */
    PpMbcard selectByPrimaryKey(Integer mbcardId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pp_mbcard
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") PpMbcard record, @Param("example") PpMbcardExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pp_mbcard
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") PpMbcard record, @Param("example") PpMbcardExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pp_mbcard
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(PpMbcard record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pp_mbcard
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(PpMbcard record);
}