package com.rs.ocp.domain.mappers;

import com.rs.ocp.domain.endity.PpPassport;
import com.rs.ocp.domain.endity.PpPassportExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface PpPassportMapper {

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table pp_passport
     *
     * @mbggenerated
     */
    int countByExample(PpPassportExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table pp_passport
     *
     * @mbggenerated
     */
    int deleteByExample(PpPassportExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table pp_passport
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer passportPid);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table pp_passport
     *
     * @mbggenerated
     */
    int insert(PpPassport record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table pp_passport
     *
     * @mbggenerated
     */
    int insertSelective(PpPassport record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table pp_passport
     *
     * @mbggenerated
     */
    List<PpPassport> selectByExample(PpPassportExample example);

    List<PpPassport> selectByExampleLimit1(PpPassportExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table pp_passport
     *
     * @mbggenerated
     */
    PpPassport selectByPrimaryKey(Integer passportPid);

    PpPassport selectByPrimaryKeyLimit1(Integer passportPid);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table pp_passport
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") PpPassport record, @Param("example") PpPassportExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table pp_passport
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") PpPassport record, @Param("example") PpPassportExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table pp_passport
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(PpPassport record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table pp_passport
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(PpPassport record);
}