package com.rs.ocp.domain.mappers;

import com.rs.ocp.domain.endity.PpStatus;
import com.rs.ocp.domain.endity.PpStatusExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface PpStatusMapper {

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table pp_status
     *
     * @mbggenerated
     */
    int countByExample(PpStatusExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table pp_status
     *
     * @mbggenerated
     */
    int deleteByExample(PpStatusExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table pp_status
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer statusPid);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table pp_status
     *
     * @mbggenerated
     */
    int insert(PpStatus record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table pp_status
     *
     * @mbggenerated
     */
    int insertSelective(PpStatus record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table pp_status
     *
     * @mbggenerated
     */
    List<PpStatus> selectByExample(PpStatusExample example);

    List<PpStatus> selectByExampleLimit1(PpStatusExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table pp_status
     *
     * @mbggenerated
     */
    PpStatus selectByPrimaryKey(Integer statusPid);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table pp_status
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") PpStatus record, @Param("example") PpStatusExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table pp_status
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") PpStatus record, @Param("example") PpStatusExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table pp_status
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(PpStatus record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table pp_status
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(PpStatus record);
}