package com.rs.ocp.domain.mappers;

import com.rs.ocp.domain.endity.PpUser;
import com.rs.ocp.domain.endity.PpUserExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface PpUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pp_user
     *
     * @mbggenerated
     */
    int countByExample(PpUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pp_user
     *
     * @mbggenerated
     */
    int deleteByExample(PpUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pp_user
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer userPid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pp_user
     *
     * @mbggenerated
     */
    int insert(PpUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pp_user
     *
     * @mbggenerated
     */
    int insertSelective(PpUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pp_user
     *
     * @mbggenerated
     */
    List<PpUser> selectByExample(PpUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pp_user
     *
     * @mbggenerated
     */
    PpUser selectByPrimaryKey(Integer userPid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pp_user
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") PpUser record, @Param("example") PpUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pp_user
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") PpUser record, @Param("example") PpUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pp_user
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(PpUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pp_user
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(PpUser record);
}