package com.rs.ocp.domain.endity;

public class AccAccpwd {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column acc_accpwd.accpwd_id
     *
     * @mbggenerated
     */
    private Integer accpwdId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column acc_accpwd.accpwd_accid
     *
     * @mbggenerated
     */
    private Integer accpwdAccid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column acc_accpwd.accpwd_pwd
     *
     * @mbggenerated
     */
    private String accpwdPwd;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column acc_accpwd.accpwd_id
     *
     * @return the value of acc_accpwd.accpwd_id
     *
     * @mbggenerated
     */
    public Integer getAccpwdId() {
        return accpwdId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column acc_accpwd.accpwd_id
     *
     * @param accpwdId the value for acc_accpwd.accpwd_id
     *
     * @mbggenerated
     */
    public void setAccpwdId(Integer accpwdId) {
        this.accpwdId = accpwdId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column acc_accpwd.accpwd_accid
     *
     * @return the value of acc_accpwd.accpwd_accid
     *
     * @mbggenerated
     */
    public Integer getAccpwdAccid() {
        return accpwdAccid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column acc_accpwd.accpwd_accid
     *
     * @param accpwdAccid the value for acc_accpwd.accpwd_accid
     *
     * @mbggenerated
     */
    public void setAccpwdAccid(Integer accpwdAccid) {
        this.accpwdAccid = accpwdAccid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column acc_accpwd.accpwd_pwd
     *
     * @return the value of acc_accpwd.accpwd_pwd
     *
     * @mbggenerated
     */
    public String getAccpwdPwd() {
        return accpwdPwd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column acc_accpwd.accpwd_pwd
     *
     * @param accpwdPwd the value for acc_accpwd.accpwd_pwd
     *
     * @mbggenerated
     */
    public void setAccpwdPwd(String accpwdPwd) {
        this.accpwdPwd = accpwdPwd == null ? null : accpwdPwd.trim();
    }
}