package com.rs.ocp.domain.endity;

public class AccAccount {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column acc_account.account_id
     *
     * @mbggenerated
     */
    private Integer accountId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column acc_account.account_pid
     *
     * @mbggenerated
     */
    private Integer accountPid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column acc_account.account_gameid
     *
     * @mbggenerated
     */
    private Integer accountGameid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column acc_account.account_areaid
     *
     * @mbggenerated
     */
    private Integer accountAreaid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column acc_account.account_serverid
     *
     * @mbggenerated
     */
    private Integer accountServerid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column acc_account.account_currency
     *
     * @mbggenerated
     */
    private Integer accountCurrency;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column acc_account.account_points
     *
     * @mbggenerated
     */
    private Integer accountPoints;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column acc_account.account_pointstrial
     *
     * @mbggenerated
     */
    private Integer accountPointstrial;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column acc_account.account_deadline
     *
     * @mbggenerated
     */
    private Integer accountDeadline;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column acc_account.account_status
     *
     * @mbggenerated
     */
    private Integer accountStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column acc_account.account_isrmb
     *
     * @mbggenerated
     */
    private Integer accountIsrmb;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column acc_account.account_time
     *
     * @mbggenerated
     */
    private Integer accountTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column acc_account.account_id
     *
     * @return the value of acc_account.account_id
     *
     * @mbggenerated
     */
    public Integer getAccountId() {
        return accountId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column acc_account.account_id
     *
     * @param accountId the value for acc_account.account_id
     *
     * @mbggenerated
     */
    public void setAccountId(Integer accountId) {
        this.accountId = accountId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column acc_account.account_pid
     *
     * @return the value of acc_account.account_pid
     *
     * @mbggenerated
     */
    public Integer getAccountPid() {
        return accountPid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column acc_account.account_pid
     *
     * @param accountPid the value for acc_account.account_pid
     *
     * @mbggenerated
     */
    public void setAccountPid(Integer accountPid) {
        this.accountPid = accountPid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column acc_account.account_gameid
     *
     * @return the value of acc_account.account_gameid
     *
     * @mbggenerated
     */
    public Integer getAccountGameid() {
        return accountGameid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column acc_account.account_gameid
     *
     * @param accountGameid the value for acc_account.account_gameid
     *
     * @mbggenerated
     */
    public void setAccountGameid(Integer accountGameid) {
        this.accountGameid = accountGameid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column acc_account.account_areaid
     *
     * @return the value of acc_account.account_areaid
     *
     * @mbggenerated
     */
    public Integer getAccountAreaid() {
        return accountAreaid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column acc_account.account_areaid
     *
     * @param accountAreaid the value for acc_account.account_areaid
     *
     * @mbggenerated
     */
    public void setAccountAreaid(Integer accountAreaid) {
        this.accountAreaid = accountAreaid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column acc_account.account_serverid
     *
     * @return the value of acc_account.account_serverid
     *
     * @mbggenerated
     */
    public Integer getAccountServerid() {
        return accountServerid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column acc_account.account_serverid
     *
     * @param accountServerid the value for acc_account.account_serverid
     *
     * @mbggenerated
     */
    public void setAccountServerid(Integer accountServerid) {
        this.accountServerid = accountServerid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column acc_account.account_currency
     *
     * @return the value of acc_account.account_currency
     *
     * @mbggenerated
     */
    public Integer getAccountCurrency() {
        return accountCurrency;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column acc_account.account_currency
     *
     * @param accountCurrency the value for acc_account.account_currency
     *
     * @mbggenerated
     */
    public void setAccountCurrency(Integer accountCurrency) {
        this.accountCurrency = accountCurrency;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column acc_account.account_points
     *
     * @return the value of acc_account.account_points
     *
     * @mbggenerated
     */
    public Integer getAccountPoints() {
        return accountPoints;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column acc_account.account_points
     *
     * @param accountPoints the value for acc_account.account_points
     *
     * @mbggenerated
     */
    public void setAccountPoints(Integer accountPoints) {
        this.accountPoints = accountPoints;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column acc_account.account_pointstrial
     *
     * @return the value of acc_account.account_pointstrial
     *
     * @mbggenerated
     */
    public Integer getAccountPointstrial() {
        return accountPointstrial;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column acc_account.account_pointstrial
     *
     * @param accountPointstrial the value for acc_account.account_pointstrial
     *
     * @mbggenerated
     */
    public void setAccountPointstrial(Integer accountPointstrial) {
        this.accountPointstrial = accountPointstrial;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column acc_account.account_deadline
     *
     * @return the value of acc_account.account_deadline
     *
     * @mbggenerated
     */
    public Integer getAccountDeadline() {
        return accountDeadline;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column acc_account.account_deadline
     *
     * @param accountDeadline the value for acc_account.account_deadline
     *
     * @mbggenerated
     */
    public void setAccountDeadline(Integer accountDeadline) {
        this.accountDeadline = accountDeadline;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column acc_account.account_status
     *
     * @return the value of acc_account.account_status
     *
     * @mbggenerated
     */
    public Integer getAccountStatus() {
        return accountStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column acc_account.account_status
     *
     * @param accountStatus the value for acc_account.account_status
     *
     * @mbggenerated
     */
    public void setAccountStatus(Integer accountStatus) {
        this.accountStatus = accountStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column acc_account.account_isrmb
     *
     * @return the value of acc_account.account_isrmb
     *
     * @mbggenerated
     */
    public Integer getAccountIsrmb() {
        return accountIsrmb;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column acc_account.account_isrmb
     *
     * @param accountIsrmb the value for acc_account.account_isrmb
     *
     * @mbggenerated
     */
    public void setAccountIsrmb(Integer accountIsrmb) {
        this.accountIsrmb = accountIsrmb;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column acc_account.account_time
     *
     * @return the value of acc_account.account_time
     *
     * @mbggenerated
     */
    public Integer getAccountTime() {
        return accountTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column acc_account.account_time
     *
     * @param accountTime the value for acc_account.account_time
     *
     * @mbggenerated
     */
    public void setAccountTime(Integer accountTime) {
        this.accountTime = accountTime;
    }
}