package com.rs.ocp.domain.endity;

public class GameArea {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column game_area.area_id
     *
     * @mbggenerated
     */
    private Integer areaId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column game_area.area_name
     *
     * @mbggenerated
     */
    private String areaName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column game_area.area_gameid
     *
     * @mbggenerated
     */
    private Integer areaGameid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column game_area.area_status
     *
     * @mbggenerated
     */
    private Integer areaStatus;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column game_area.area_id
     *
     * @return the value of game_area.area_id
     *
     * @mbggenerated
     */
    public Integer getAreaId() {
        return areaId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column game_area.area_id
     *
     * @param areaId the value for game_area.area_id
     *
     * @mbggenerated
     */
    public void setAreaId(Integer areaId) {
        this.areaId = areaId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column game_area.area_name
     *
     * @return the value of game_area.area_name
     *
     * @mbggenerated
     */
    public String getAreaName() {
        return areaName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column game_area.area_name
     *
     * @param areaName the value for game_area.area_name
     *
     * @mbggenerated
     */
    public void setAreaName(String areaName) {
        this.areaName = areaName == null ? null : areaName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column game_area.area_gameid
     *
     * @return the value of game_area.area_gameid
     *
     * @mbggenerated
     */
    public Integer getAreaGameid() {
        return areaGameid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column game_area.area_gameid
     *
     * @param areaGameid the value for game_area.area_gameid
     *
     * @mbggenerated
     */
    public void setAreaGameid(Integer areaGameid) {
        this.areaGameid = areaGameid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column game_area.area_status
     *
     * @return the value of game_area.area_status
     *
     * @mbggenerated
     */
    public Integer getAreaStatus() {
        return areaStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column game_area.area_status
     *
     * @param areaStatus the value for game_area.area_status
     *
     * @mbggenerated
     */
    public void setAreaStatus(Integer areaStatus) {
        this.areaStatus = areaStatus;
    }
}