package com.rs.ocp.domain.endity;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class GameLoginExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table game_login
     *
     * @mbggenerated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table game_login
     *
     * @mbggenerated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table game_login
     *
     * @mbggenerated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table game_login
     *
     * @mbggenerated
     */
    public GameLoginExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table game_login
     *
     * @mbggenerated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table game_login
     *
     * @mbggenerated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table game_login
     *
     * @mbggenerated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table game_login
     *
     * @mbggenerated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table game_login
     *
     * @mbggenerated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table game_login
     *
     * @mbggenerated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table game_login
     *
     * @mbggenerated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table game_login
     *
     * @mbggenerated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table game_login
     *
     * @mbggenerated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table game_login
     *
     * @mbggenerated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table game_login
     *
     * @mbggenerated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andLoginIdIsNull() {
            addCriterion("login_id is null");
            return (Criteria) this;
        }

        public Criteria andLoginIdIsNotNull() {
            addCriterion("login_id is not null");
            return (Criteria) this;
        }

        public Criteria andLoginIdEqualTo(Integer value) {
            addCriterion("login_id =", value, "loginId");
            return (Criteria) this;
        }

        public Criteria andLoginIdNotEqualTo(Integer value) {
            addCriterion("login_id <>", value, "loginId");
            return (Criteria) this;
        }

        public Criteria andLoginIdGreaterThan(Integer value) {
            addCriterion("login_id >", value, "loginId");
            return (Criteria) this;
        }

        public Criteria andLoginIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("login_id >=", value, "loginId");
            return (Criteria) this;
        }

        public Criteria andLoginIdLessThan(Integer value) {
            addCriterion("login_id <", value, "loginId");
            return (Criteria) this;
        }

        public Criteria andLoginIdLessThanOrEqualTo(Integer value) {
            addCriterion("login_id <=", value, "loginId");
            return (Criteria) this;
        }

        public Criteria andLoginIdIn(List<Integer> values) {
            addCriterion("login_id in", values, "loginId");
            return (Criteria) this;
        }

        public Criteria andLoginIdNotIn(List<Integer> values) {
            addCriterion("login_id not in", values, "loginId");
            return (Criteria) this;
        }

        public Criteria andLoginIdBetween(Integer value1, Integer value2) {
            addCriterion("login_id between", value1, value2, "loginId");
            return (Criteria) this;
        }

        public Criteria andLoginIdNotBetween(Integer value1, Integer value2) {
            addCriterion("login_id not between", value1, value2, "loginId");
            return (Criteria) this;
        }

        public Criteria andLoginUseridIsNull() {
            addCriterion("login_userid is null");
            return (Criteria) this;
        }

        public Criteria andLoginUseridIsNotNull() {
            addCriterion("login_userid is not null");
            return (Criteria) this;
        }

        public Criteria andLoginUseridEqualTo(Integer value) {
            addCriterion("login_userid =", value, "loginUserid");
            return (Criteria) this;
        }

        public Criteria andLoginUseridNotEqualTo(Integer value) {
            addCriterion("login_userid <>", value, "loginUserid");
            return (Criteria) this;
        }

        public Criteria andLoginUseridGreaterThan(Integer value) {
            addCriterion("login_userid >", value, "loginUserid");
            return (Criteria) this;
        }

        public Criteria andLoginUseridGreaterThanOrEqualTo(Integer value) {
            addCriterion("login_userid >=", value, "loginUserid");
            return (Criteria) this;
        }

        public Criteria andLoginUseridLessThan(Integer value) {
            addCriterion("login_userid <", value, "loginUserid");
            return (Criteria) this;
        }

        public Criteria andLoginUseridLessThanOrEqualTo(Integer value) {
            addCriterion("login_userid <=", value, "loginUserid");
            return (Criteria) this;
        }

        public Criteria andLoginUseridIn(List<Integer> values) {
            addCriterion("login_userid in", values, "loginUserid");
            return (Criteria) this;
        }

        public Criteria andLoginUseridNotIn(List<Integer> values) {
            addCriterion("login_userid not in", values, "loginUserid");
            return (Criteria) this;
        }

        public Criteria andLoginUseridBetween(Integer value1, Integer value2) {
            addCriterion("login_userid between", value1, value2, "loginUserid");
            return (Criteria) this;
        }

        public Criteria andLoginUseridNotBetween(Integer value1, Integer value2) {
            addCriterion("login_userid not between", value1, value2, "loginUserid");
            return (Criteria) this;
        }

        public Criteria andLoginGameidIsNull() {
            addCriterion("login_gameid is null");
            return (Criteria) this;
        }

        public Criteria andLoginGameidIsNotNull() {
            addCriterion("login_gameid is not null");
            return (Criteria) this;
        }

        public Criteria andLoginGameidEqualTo(Integer value) {
            addCriterion("login_gameid =", value, "loginGameid");
            return (Criteria) this;
        }

        public Criteria andLoginGameidNotEqualTo(Integer value) {
            addCriterion("login_gameid <>", value, "loginGameid");
            return (Criteria) this;
        }

        public Criteria andLoginGameidGreaterThan(Integer value) {
            addCriterion("login_gameid >", value, "loginGameid");
            return (Criteria) this;
        }

        public Criteria andLoginGameidGreaterThanOrEqualTo(Integer value) {
            addCriterion("login_gameid >=", value, "loginGameid");
            return (Criteria) this;
        }

        public Criteria andLoginGameidLessThan(Integer value) {
            addCriterion("login_gameid <", value, "loginGameid");
            return (Criteria) this;
        }

        public Criteria andLoginGameidLessThanOrEqualTo(Integer value) {
            addCriterion("login_gameid <=", value, "loginGameid");
            return (Criteria) this;
        }

        public Criteria andLoginGameidIn(List<Integer> values) {
            addCriterion("login_gameid in", values, "loginGameid");
            return (Criteria) this;
        }

        public Criteria andLoginGameidNotIn(List<Integer> values) {
            addCriterion("login_gameid not in", values, "loginGameid");
            return (Criteria) this;
        }

        public Criteria andLoginGameidBetween(Integer value1, Integer value2) {
            addCriterion("login_gameid between", value1, value2, "loginGameid");
            return (Criteria) this;
        }

        public Criteria andLoginGameidNotBetween(Integer value1, Integer value2) {
            addCriterion("login_gameid not between", value1, value2, "loginGameid");
            return (Criteria) this;
        }

        public Criteria andLoginAreaidIsNull() {
            addCriterion("login_areaid is null");
            return (Criteria) this;
        }

        public Criteria andLoginAreaidIsNotNull() {
            addCriterion("login_areaid is not null");
            return (Criteria) this;
        }

        public Criteria andLoginAreaidEqualTo(Integer value) {
            addCriterion("login_areaid =", value, "loginAreaid");
            return (Criteria) this;
        }

        public Criteria andLoginAreaidNotEqualTo(Integer value) {
            addCriterion("login_areaid <>", value, "loginAreaid");
            return (Criteria) this;
        }

        public Criteria andLoginAreaidGreaterThan(Integer value) {
            addCriterion("login_areaid >", value, "loginAreaid");
            return (Criteria) this;
        }

        public Criteria andLoginAreaidGreaterThanOrEqualTo(Integer value) {
            addCriterion("login_areaid >=", value, "loginAreaid");
            return (Criteria) this;
        }

        public Criteria andLoginAreaidLessThan(Integer value) {
            addCriterion("login_areaid <", value, "loginAreaid");
            return (Criteria) this;
        }

        public Criteria andLoginAreaidLessThanOrEqualTo(Integer value) {
            addCriterion("login_areaid <=", value, "loginAreaid");
            return (Criteria) this;
        }

        public Criteria andLoginAreaidIn(List<Integer> values) {
            addCriterion("login_areaid in", values, "loginAreaid");
            return (Criteria) this;
        }

        public Criteria andLoginAreaidNotIn(List<Integer> values) {
            addCriterion("login_areaid not in", values, "loginAreaid");
            return (Criteria) this;
        }

        public Criteria andLoginAreaidBetween(Integer value1, Integer value2) {
            addCriterion("login_areaid between", value1, value2, "loginAreaid");
            return (Criteria) this;
        }

        public Criteria andLoginAreaidNotBetween(Integer value1, Integer value2) {
            addCriterion("login_areaid not between", value1, value2, "loginAreaid");
            return (Criteria) this;
        }

        public Criteria andLoginServeridIsNull() {
            addCriterion("login_serverid is null");
            return (Criteria) this;
        }

        public Criteria andLoginServeridIsNotNull() {
            addCriterion("login_serverid is not null");
            return (Criteria) this;
        }

        public Criteria andLoginServeridEqualTo(Integer value) {
            addCriterion("login_serverid =", value, "loginServerid");
            return (Criteria) this;
        }

        public Criteria andLoginServeridNotEqualTo(Integer value) {
            addCriterion("login_serverid <>", value, "loginServerid");
            return (Criteria) this;
        }

        public Criteria andLoginServeridGreaterThan(Integer value) {
            addCriterion("login_serverid >", value, "loginServerid");
            return (Criteria) this;
        }

        public Criteria andLoginServeridGreaterThanOrEqualTo(Integer value) {
            addCriterion("login_serverid >=", value, "loginServerid");
            return (Criteria) this;
        }

        public Criteria andLoginServeridLessThan(Integer value) {
            addCriterion("login_serverid <", value, "loginServerid");
            return (Criteria) this;
        }

        public Criteria andLoginServeridLessThanOrEqualTo(Integer value) {
            addCriterion("login_serverid <=", value, "loginServerid");
            return (Criteria) this;
        }

        public Criteria andLoginServeridIn(List<Integer> values) {
            addCriterion("login_serverid in", values, "loginServerid");
            return (Criteria) this;
        }

        public Criteria andLoginServeridNotIn(List<Integer> values) {
            addCriterion("login_serverid not in", values, "loginServerid");
            return (Criteria) this;
        }

        public Criteria andLoginServeridBetween(Integer value1, Integer value2) {
            addCriterion("login_serverid between", value1, value2, "loginServerid");
            return (Criteria) this;
        }

        public Criteria andLoginServeridNotBetween(Integer value1, Integer value2) {
            addCriterion("login_serverid not between", value1, value2, "loginServerid");
            return (Criteria) this;
        }

        public Criteria andLoginTimeIsNull() {
            addCriterion("login_time is null");
            return (Criteria) this;
        }

        public Criteria andLoginTimeIsNotNull() {
            addCriterion("login_time is not null");
            return (Criteria) this;
        }

        public Criteria andLoginTimeEqualTo(Date value) {
            addCriterion("login_time =", value, "loginTime");
            return (Criteria) this;
        }

        public Criteria andLoginTimeNotEqualTo(Date value) {
            addCriterion("login_time <>", value, "loginTime");
            return (Criteria) this;
        }

        public Criteria andLoginTimeGreaterThan(Date value) {
            addCriterion("login_time >", value, "loginTime");
            return (Criteria) this;
        }

        public Criteria andLoginTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("login_time >=", value, "loginTime");
            return (Criteria) this;
        }

        public Criteria andLoginTimeLessThan(Date value) {
            addCriterion("login_time <", value, "loginTime");
            return (Criteria) this;
        }

        public Criteria andLoginTimeLessThanOrEqualTo(Date value) {
            addCriterion("login_time <=", value, "loginTime");
            return (Criteria) this;
        }

        public Criteria andLoginTimeIn(List<Date> values) {
            addCriterion("login_time in", values, "loginTime");
            return (Criteria) this;
        }

        public Criteria andLoginTimeNotIn(List<Date> values) {
            addCriterion("login_time not in", values, "loginTime");
            return (Criteria) this;
        }

        public Criteria andLoginTimeBetween(Date value1, Date value2) {
            addCriterion("login_time between", value1, value2, "loginTime");
            return (Criteria) this;
        }

        public Criteria andLoginTimeNotBetween(Date value1, Date value2) {
            addCriterion("login_time not between", value1, value2, "loginTime");
            return (Criteria) this;
        }

        public Criteria andLoginTypeIsNull() {
            addCriterion("login_type is null");
            return (Criteria) this;
        }

        public Criteria andLoginTypeIsNotNull() {
            addCriterion("login_type is not null");
            return (Criteria) this;
        }

        public Criteria andLoginTypeEqualTo(Integer value) {
            addCriterion("login_type =", value, "loginType");
            return (Criteria) this;
        }

        public Criteria andLoginTypeNotEqualTo(Integer value) {
            addCriterion("login_type <>", value, "loginType");
            return (Criteria) this;
        }

        public Criteria andLoginTypeGreaterThan(Integer value) {
            addCriterion("login_type >", value, "loginType");
            return (Criteria) this;
        }

        public Criteria andLoginTypeGreaterThanOrEqualTo(Integer value) {
            addCriterion("login_type >=", value, "loginType");
            return (Criteria) this;
        }

        public Criteria andLoginTypeLessThan(Integer value) {
            addCriterion("login_type <", value, "loginType");
            return (Criteria) this;
        }

        public Criteria andLoginTypeLessThanOrEqualTo(Integer value) {
            addCriterion("login_type <=", value, "loginType");
            return (Criteria) this;
        }

        public Criteria andLoginTypeIn(List<Integer> values) {
            addCriterion("login_type in", values, "loginType");
            return (Criteria) this;
        }

        public Criteria andLoginTypeNotIn(List<Integer> values) {
            addCriterion("login_type not in", values, "loginType");
            return (Criteria) this;
        }

        public Criteria andLoginTypeBetween(Integer value1, Integer value2) {
            addCriterion("login_type between", value1, value2, "loginType");
            return (Criteria) this;
        }

        public Criteria andLoginTypeNotBetween(Integer value1, Integer value2) {
            addCriterion("login_type not between", value1, value2, "loginType");
            return (Criteria) this;
        }

        public Criteria andLoginSessionidIsNull() {
            addCriterion("login_sessionid is null");
            return (Criteria) this;
        }

        public Criteria andLoginSessionidIsNotNull() {
            addCriterion("login_sessionid is not null");
            return (Criteria) this;
        }

        public Criteria andLoginSessionidEqualTo(Integer value) {
            addCriterion("login_sessionid =", value, "loginSessionid");
            return (Criteria) this;
        }

        public Criteria andLoginSessionidNotEqualTo(Integer value) {
            addCriterion("login_sessionid <>", value, "loginSessionid");
            return (Criteria) this;
        }

        public Criteria andLoginSessionidGreaterThan(Integer value) {
            addCriterion("login_sessionid >", value, "loginSessionid");
            return (Criteria) this;
        }

        public Criteria andLoginSessionidGreaterThanOrEqualTo(Integer value) {
            addCriterion("login_sessionid >=", value, "loginSessionid");
            return (Criteria) this;
        }

        public Criteria andLoginSessionidLessThan(Integer value) {
            addCriterion("login_sessionid <", value, "loginSessionid");
            return (Criteria) this;
        }

        public Criteria andLoginSessionidLessThanOrEqualTo(Integer value) {
            addCriterion("login_sessionid <=", value, "loginSessionid");
            return (Criteria) this;
        }

        public Criteria andLoginSessionidIn(List<Integer> values) {
            addCriterion("login_sessionid in", values, "loginSessionid");
            return (Criteria) this;
        }

        public Criteria andLoginSessionidNotIn(List<Integer> values) {
            addCriterion("login_sessionid not in", values, "loginSessionid");
            return (Criteria) this;
        }

        public Criteria andLoginSessionidBetween(Integer value1, Integer value2) {
            addCriterion("login_sessionid between", value1, value2, "loginSessionid");
            return (Criteria) this;
        }

        public Criteria andLoginSessionidNotBetween(Integer value1, Integer value2) {
            addCriterion("login_sessionid not between", value1, value2, "loginSessionid");
            return (Criteria) this;
        }

        public Criteria andLoginClientipIsNull() {
            addCriterion("login_clientip is null");
            return (Criteria) this;
        }

        public Criteria andLoginClientipIsNotNull() {
            addCriterion("login_clientip is not null");
            return (Criteria) this;
        }

        public Criteria andLoginClientipEqualTo(String value) {
            addCriterion("login_clientip =", value, "loginClientip");
            return (Criteria) this;
        }

        public Criteria andLoginClientipNotEqualTo(String value) {
            addCriterion("login_clientip <>", value, "loginClientip");
            return (Criteria) this;
        }

        public Criteria andLoginClientipGreaterThan(String value) {
            addCriterion("login_clientip >", value, "loginClientip");
            return (Criteria) this;
        }

        public Criteria andLoginClientipGreaterThanOrEqualTo(String value) {
            addCriterion("login_clientip >=", value, "loginClientip");
            return (Criteria) this;
        }

        public Criteria andLoginClientipLessThan(String value) {
            addCriterion("login_clientip <", value, "loginClientip");
            return (Criteria) this;
        }

        public Criteria andLoginClientipLessThanOrEqualTo(String value) {
            addCriterion("login_clientip <=", value, "loginClientip");
            return (Criteria) this;
        }

        public Criteria andLoginClientipLike(String value) {
            addCriterion("login_clientip like", value, "loginClientip");
            return (Criteria) this;
        }

        public Criteria andLoginClientipNotLike(String value) {
            addCriterion("login_clientip not like", value, "loginClientip");
            return (Criteria) this;
        }

        public Criteria andLoginClientipIn(List<String> values) {
            addCriterion("login_clientip in", values, "loginClientip");
            return (Criteria) this;
        }

        public Criteria andLoginClientipNotIn(List<String> values) {
            addCriterion("login_clientip not in", values, "loginClientip");
            return (Criteria) this;
        }

        public Criteria andLoginClientipBetween(String value1, String value2) {
            addCriterion("login_clientip between", value1, value2, "loginClientip");
            return (Criteria) this;
        }

        public Criteria andLoginClientipNotBetween(String value1, String value2) {
            addCriterion("login_clientip not between", value1, value2, "loginClientip");
            return (Criteria) this;
        }

        public Criteria andLoginClientportIsNull() {
            addCriterion("login_clientport is null");
            return (Criteria) this;
        }

        public Criteria andLoginClientportIsNotNull() {
            addCriterion("login_clientport is not null");
            return (Criteria) this;
        }

        public Criteria andLoginClientportEqualTo(Integer value) {
            addCriterion("login_clientport =", value, "loginClientport");
            return (Criteria) this;
        }

        public Criteria andLoginClientportNotEqualTo(Integer value) {
            addCriterion("login_clientport <>", value, "loginClientport");
            return (Criteria) this;
        }

        public Criteria andLoginClientportGreaterThan(Integer value) {
            addCriterion("login_clientport >", value, "loginClientport");
            return (Criteria) this;
        }

        public Criteria andLoginClientportGreaterThanOrEqualTo(Integer value) {
            addCriterion("login_clientport >=", value, "loginClientport");
            return (Criteria) this;
        }

        public Criteria andLoginClientportLessThan(Integer value) {
            addCriterion("login_clientport <", value, "loginClientport");
            return (Criteria) this;
        }

        public Criteria andLoginClientportLessThanOrEqualTo(Integer value) {
            addCriterion("login_clientport <=", value, "loginClientport");
            return (Criteria) this;
        }

        public Criteria andLoginClientportIn(List<Integer> values) {
            addCriterion("login_clientport in", values, "loginClientport");
            return (Criteria) this;
        }

        public Criteria andLoginClientportNotIn(List<Integer> values) {
            addCriterion("login_clientport not in", values, "loginClientport");
            return (Criteria) this;
        }

        public Criteria andLoginClientportBetween(Integer value1, Integer value2) {
            addCriterion("login_clientport between", value1, value2, "loginClientport");
            return (Criteria) this;
        }

        public Criteria andLoginClientportNotBetween(Integer value1, Integer value2) {
            addCriterion("login_clientport not between", value1, value2, "loginClientport");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table game_login
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table game_login
     *
     * @mbggenerated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}