package com.rs.ocp.domain.endity;

import java.util.Date;

public class GameLoginsession {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column game_loginsession.session_id
     *
     * @mbggenerated
     */
    private Integer sessionId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column game_loginsession.session_key
     *
     * @mbggenerated
     */
    private String sessionKey;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column game_loginsession.session_pid
     *
     * @mbggenerated
     */
    private Integer sessionPid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column game_loginsession.session_serverid
     *
     * @mbggenerated
     */
    private Integer sessionServerid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column game_loginsession.session_awake
     *
     * @mbggenerated
     */
    private Integer sessionAwake;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column game_loginsession.session_time
     *
     * @mbggenerated
     */
    private Date sessionTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column game_loginsession.session_id
     *
     * @return the value of game_loginsession.session_id
     *
     * @mbggenerated
     */
    public Integer getSessionId() {
        return sessionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column game_loginsession.session_id
     *
     * @param sessionId the value for game_loginsession.session_id
     *
     * @mbggenerated
     */
    public void setSessionId(Integer sessionId) {
        this.sessionId = sessionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column game_loginsession.session_key
     *
     * @return the value of game_loginsession.session_key
     *
     * @mbggenerated
     */
    public String getSessionKey() {
        return sessionKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column game_loginsession.session_key
     *
     * @param sessionKey the value for game_loginsession.session_key
     *
     * @mbggenerated
     */
    public void setSessionKey(String sessionKey) {
        this.sessionKey = sessionKey == null ? null : sessionKey.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column game_loginsession.session_pid
     *
     * @return the value of game_loginsession.session_pid
     *
     * @mbggenerated
     */
    public Integer getSessionPid() {
        return sessionPid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column game_loginsession.session_pid
     *
     * @param sessionPid the value for game_loginsession.session_pid
     *
     * @mbggenerated
     */
    public void setSessionPid(Integer sessionPid) {
        this.sessionPid = sessionPid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column game_loginsession.session_serverid
     *
     * @return the value of game_loginsession.session_serverid
     *
     * @mbggenerated
     */
    public Integer getSessionServerid() {
        return sessionServerid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column game_loginsession.session_serverid
     *
     * @param sessionServerid the value for game_loginsession.session_serverid
     *
     * @mbggenerated
     */
    public void setSessionServerid(Integer sessionServerid) {
        this.sessionServerid = sessionServerid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column game_loginsession.session_awake
     *
     * @return the value of game_loginsession.session_awake
     *
     * @mbggenerated
     */
    public Integer getSessionAwake() {
        return sessionAwake;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column game_loginsession.session_awake
     *
     * @param sessionAwake the value for game_loginsession.session_awake
     *
     * @mbggenerated
     */
    public void setSessionAwake(Integer sessionAwake) {
        this.sessionAwake = sessionAwake;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column game_loginsession.session_time
     *
     * @return the value of game_loginsession.session_time
     *
     * @mbggenerated
     */
    public Date getSessionTime() {
        return sessionTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column game_loginsession.session_time
     *
     * @param sessionTime the value for game_loginsession.session_time
     *
     * @mbggenerated
     */
    public void setSessionTime(Date sessionTime) {
        this.sessionTime = sessionTime;
    }
}