package com.rs.ocp.domain.endity;

import java.util.ArrayList;
import java.util.List;

public class GameServerExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table game_server
     *
     * @mbggenerated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table game_server
     *
     * @mbggenerated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table game_server
     *
     * @mbggenerated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table game_server
     *
     * @mbggenerated
     */
    public GameServerExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table game_server
     *
     * @mbggenerated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table game_server
     *
     * @mbggenerated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table game_server
     *
     * @mbggenerated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table game_server
     *
     * @mbggenerated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table game_server
     *
     * @mbggenerated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table game_server
     *
     * @mbggenerated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table game_server
     *
     * @mbggenerated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table game_server
     *
     * @mbggenerated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table game_server
     *
     * @mbggenerated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table game_server
     *
     * @mbggenerated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table game_server
     *
     * @mbggenerated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andServerIdIsNull() {
            addCriterion("server_id is null");
            return (Criteria) this;
        }

        public Criteria andServerIdIsNotNull() {
            addCriterion("server_id is not null");
            return (Criteria) this;
        }

        public Criteria andServerIdEqualTo(Integer value) {
            addCriterion("server_id =", value, "serverId");
            return (Criteria) this;
        }

        public Criteria andServerIdNotEqualTo(Integer value) {
            addCriterion("server_id <>", value, "serverId");
            return (Criteria) this;
        }

        public Criteria andServerIdGreaterThan(Integer value) {
            addCriterion("server_id >", value, "serverId");
            return (Criteria) this;
        }

        public Criteria andServerIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("server_id >=", value, "serverId");
            return (Criteria) this;
        }

        public Criteria andServerIdLessThan(Integer value) {
            addCriterion("server_id <", value, "serverId");
            return (Criteria) this;
        }

        public Criteria andServerIdLessThanOrEqualTo(Integer value) {
            addCriterion("server_id <=", value, "serverId");
            return (Criteria) this;
        }

        public Criteria andServerIdIn(List<Integer> values) {
            addCriterion("server_id in", values, "serverId");
            return (Criteria) this;
        }

        public Criteria andServerIdNotIn(List<Integer> values) {
            addCriterion("server_id not in", values, "serverId");
            return (Criteria) this;
        }

        public Criteria andServerIdBetween(Integer value1, Integer value2) {
            addCriterion("server_id between", value1, value2, "serverId");
            return (Criteria) this;
        }

        public Criteria andServerIdNotBetween(Integer value1, Integer value2) {
            addCriterion("server_id not between", value1, value2, "serverId");
            return (Criteria) this;
        }

        public Criteria andServerNameIsNull() {
            addCriterion("server_name is null");
            return (Criteria) this;
        }

        public Criteria andServerNameIsNotNull() {
            addCriterion("server_name is not null");
            return (Criteria) this;
        }

        public Criteria andServerNameEqualTo(String value) {
            addCriterion("server_name =", value, "serverName");
            return (Criteria) this;
        }

        public Criteria andServerNameNotEqualTo(String value) {
            addCriterion("server_name <>", value, "serverName");
            return (Criteria) this;
        }

        public Criteria andServerNameGreaterThan(String value) {
            addCriterion("server_name >", value, "serverName");
            return (Criteria) this;
        }

        public Criteria andServerNameGreaterThanOrEqualTo(String value) {
            addCriterion("server_name >=", value, "serverName");
            return (Criteria) this;
        }

        public Criteria andServerNameLessThan(String value) {
            addCriterion("server_name <", value, "serverName");
            return (Criteria) this;
        }

        public Criteria andServerNameLessThanOrEqualTo(String value) {
            addCriterion("server_name <=", value, "serverName");
            return (Criteria) this;
        }

        public Criteria andServerNameLike(String value) {
            addCriterion("server_name like", value, "serverName");
            return (Criteria) this;
        }

        public Criteria andServerNameNotLike(String value) {
            addCriterion("server_name not like", value, "serverName");
            return (Criteria) this;
        }

        public Criteria andServerNameIn(List<String> values) {
            addCriterion("server_name in", values, "serverName");
            return (Criteria) this;
        }

        public Criteria andServerNameNotIn(List<String> values) {
            addCriterion("server_name not in", values, "serverName");
            return (Criteria) this;
        }

        public Criteria andServerNameBetween(String value1, String value2) {
            addCriterion("server_name between", value1, value2, "serverName");
            return (Criteria) this;
        }

        public Criteria andServerNameNotBetween(String value1, String value2) {
            addCriterion("server_name not between", value1, value2, "serverName");
            return (Criteria) this;
        }

        public Criteria andServerIpIsNull() {
            addCriterion("server_ip is null");
            return (Criteria) this;
        }

        public Criteria andServerIpIsNotNull() {
            addCriterion("server_ip is not null");
            return (Criteria) this;
        }

        public Criteria andServerIpEqualTo(String value) {
            addCriterion("server_ip =", value, "serverIp");
            return (Criteria) this;
        }

        public Criteria andServerIpNotEqualTo(String value) {
            addCriterion("server_ip <>", value, "serverIp");
            return (Criteria) this;
        }

        public Criteria andServerIpGreaterThan(String value) {
            addCriterion("server_ip >", value, "serverIp");
            return (Criteria) this;
        }

        public Criteria andServerIpGreaterThanOrEqualTo(String value) {
            addCriterion("server_ip >=", value, "serverIp");
            return (Criteria) this;
        }

        public Criteria andServerIpLessThan(String value) {
            addCriterion("server_ip <", value, "serverIp");
            return (Criteria) this;
        }

        public Criteria andServerIpLessThanOrEqualTo(String value) {
            addCriterion("server_ip <=", value, "serverIp");
            return (Criteria) this;
        }

        public Criteria andServerIpLike(String value) {
            addCriterion("server_ip like", value, "serverIp");
            return (Criteria) this;
        }

        public Criteria andServerIpNotLike(String value) {
            addCriterion("server_ip not like", value, "serverIp");
            return (Criteria) this;
        }

        public Criteria andServerIpIn(List<String> values) {
            addCriterion("server_ip in", values, "serverIp");
            return (Criteria) this;
        }

        public Criteria andServerIpNotIn(List<String> values) {
            addCriterion("server_ip not in", values, "serverIp");
            return (Criteria) this;
        }

        public Criteria andServerIpBetween(String value1, String value2) {
            addCriterion("server_ip between", value1, value2, "serverIp");
            return (Criteria) this;
        }

        public Criteria andServerIpNotBetween(String value1, String value2) {
            addCriterion("server_ip not between", value1, value2, "serverIp");
            return (Criteria) this;
        }

        public Criteria andServerAreaidIsNull() {
            addCriterion("server_areaid is null");
            return (Criteria) this;
        }

        public Criteria andServerAreaidIsNotNull() {
            addCriterion("server_areaid is not null");
            return (Criteria) this;
        }

        public Criteria andServerAreaidEqualTo(Integer value) {
            addCriterion("server_areaid =", value, "serverAreaid");
            return (Criteria) this;
        }

        public Criteria andServerAreaidNotEqualTo(Integer value) {
            addCriterion("server_areaid <>", value, "serverAreaid");
            return (Criteria) this;
        }

        public Criteria andServerAreaidGreaterThan(Integer value) {
            addCriterion("server_areaid >", value, "serverAreaid");
            return (Criteria) this;
        }

        public Criteria andServerAreaidGreaterThanOrEqualTo(Integer value) {
            addCriterion("server_areaid >=", value, "serverAreaid");
            return (Criteria) this;
        }

        public Criteria andServerAreaidLessThan(Integer value) {
            addCriterion("server_areaid <", value, "serverAreaid");
            return (Criteria) this;
        }

        public Criteria andServerAreaidLessThanOrEqualTo(Integer value) {
            addCriterion("server_areaid <=", value, "serverAreaid");
            return (Criteria) this;
        }

        public Criteria andServerAreaidIn(List<Integer> values) {
            addCriterion("server_areaid in", values, "serverAreaid");
            return (Criteria) this;
        }

        public Criteria andServerAreaidNotIn(List<Integer> values) {
            addCriterion("server_areaid not in", values, "serverAreaid");
            return (Criteria) this;
        }

        public Criteria andServerAreaidBetween(Integer value1, Integer value2) {
            addCriterion("server_areaid between", value1, value2, "serverAreaid");
            return (Criteria) this;
        }

        public Criteria andServerAreaidNotBetween(Integer value1, Integer value2) {
            addCriterion("server_areaid not between", value1, value2, "serverAreaid");
            return (Criteria) this;
        }

        public Criteria andServerGameidIsNull() {
            addCriterion("server_gameid is null");
            return (Criteria) this;
        }

        public Criteria andServerGameidIsNotNull() {
            addCriterion("server_gameid is not null");
            return (Criteria) this;
        }

        public Criteria andServerGameidEqualTo(Integer value) {
            addCriterion("server_gameid =", value, "serverGameid");
            return (Criteria) this;
        }

        public Criteria andServerGameidNotEqualTo(Integer value) {
            addCriterion("server_gameid <>", value, "serverGameid");
            return (Criteria) this;
        }

        public Criteria andServerGameidGreaterThan(Integer value) {
            addCriterion("server_gameid >", value, "serverGameid");
            return (Criteria) this;
        }

        public Criteria andServerGameidGreaterThanOrEqualTo(Integer value) {
            addCriterion("server_gameid >=", value, "serverGameid");
            return (Criteria) this;
        }

        public Criteria andServerGameidLessThan(Integer value) {
            addCriterion("server_gameid <", value, "serverGameid");
            return (Criteria) this;
        }

        public Criteria andServerGameidLessThanOrEqualTo(Integer value) {
            addCriterion("server_gameid <=", value, "serverGameid");
            return (Criteria) this;
        }

        public Criteria andServerGameidIn(List<Integer> values) {
            addCriterion("server_gameid in", values, "serverGameid");
            return (Criteria) this;
        }

        public Criteria andServerGameidNotIn(List<Integer> values) {
            addCriterion("server_gameid not in", values, "serverGameid");
            return (Criteria) this;
        }

        public Criteria andServerGameidBetween(Integer value1, Integer value2) {
            addCriterion("server_gameid between", value1, value2, "serverGameid");
            return (Criteria) this;
        }

        public Criteria andServerGameidNotBetween(Integer value1, Integer value2) {
            addCriterion("server_gameid not between", value1, value2, "serverGameid");
            return (Criteria) this;
        }

        public Criteria andServerStatusIsNull() {
            addCriterion("server_status is null");
            return (Criteria) this;
        }

        public Criteria andServerStatusIsNotNull() {
            addCriterion("server_status is not null");
            return (Criteria) this;
        }

        public Criteria andServerStatusEqualTo(Integer value) {
            addCriterion("server_status =", value, "serverStatus");
            return (Criteria) this;
        }

        public Criteria andServerStatusNotEqualTo(Integer value) {
            addCriterion("server_status <>", value, "serverStatus");
            return (Criteria) this;
        }

        public Criteria andServerStatusGreaterThan(Integer value) {
            addCriterion("server_status >", value, "serverStatus");
            return (Criteria) this;
        }

        public Criteria andServerStatusGreaterThanOrEqualTo(Integer value) {
            addCriterion("server_status >=", value, "serverStatus");
            return (Criteria) this;
        }

        public Criteria andServerStatusLessThan(Integer value) {
            addCriterion("server_status <", value, "serverStatus");
            return (Criteria) this;
        }

        public Criteria andServerStatusLessThanOrEqualTo(Integer value) {
            addCriterion("server_status <=", value, "serverStatus");
            return (Criteria) this;
        }

        public Criteria andServerStatusIn(List<Integer> values) {
            addCriterion("server_status in", values, "serverStatus");
            return (Criteria) this;
        }

        public Criteria andServerStatusNotIn(List<Integer> values) {
            addCriterion("server_status not in", values, "serverStatus");
            return (Criteria) this;
        }

        public Criteria andServerStatusBetween(Integer value1, Integer value2) {
            addCriterion("server_status between", value1, value2, "serverStatus");
            return (Criteria) this;
        }

        public Criteria andServerStatusNotBetween(Integer value1, Integer value2) {
            addCriterion("server_status not between", value1, value2, "serverStatus");
            return (Criteria) this;
        }

        public Criteria andServerOpentimeIsNull() {
            addCriterion("server_opentime is null");
            return (Criteria) this;
        }

        public Criteria andServerOpentimeIsNotNull() {
            addCriterion("server_opentime is not null");
            return (Criteria) this;
        }

        public Criteria andServerOpentimeEqualTo(Integer value) {
            addCriterion("server_opentime =", value, "serverOpentime");
            return (Criteria) this;
        }

        public Criteria andServerOpentimeNotEqualTo(Integer value) {
            addCriterion("server_opentime <>", value, "serverOpentime");
            return (Criteria) this;
        }

        public Criteria andServerOpentimeGreaterThan(Integer value) {
            addCriterion("server_opentime >", value, "serverOpentime");
            return (Criteria) this;
        }

        public Criteria andServerOpentimeGreaterThanOrEqualTo(Integer value) {
            addCriterion("server_opentime >=", value, "serverOpentime");
            return (Criteria) this;
        }

        public Criteria andServerOpentimeLessThan(Integer value) {
            addCriterion("server_opentime <", value, "serverOpentime");
            return (Criteria) this;
        }

        public Criteria andServerOpentimeLessThanOrEqualTo(Integer value) {
            addCriterion("server_opentime <=", value, "serverOpentime");
            return (Criteria) this;
        }

        public Criteria andServerOpentimeIn(List<Integer> values) {
            addCriterion("server_opentime in", values, "serverOpentime");
            return (Criteria) this;
        }

        public Criteria andServerOpentimeNotIn(List<Integer> values) {
            addCriterion("server_opentime not in", values, "serverOpentime");
            return (Criteria) this;
        }

        public Criteria andServerOpentimeBetween(Integer value1, Integer value2) {
            addCriterion("server_opentime between", value1, value2, "serverOpentime");
            return (Criteria) this;
        }

        public Criteria andServerOpentimeNotBetween(Integer value1, Integer value2) {
            addCriterion("server_opentime not between", value1, value2, "serverOpentime");
            return (Criteria) this;
        }

        public Criteria andServerMergeidIsNull() {
            addCriterion("server_mergeid is null");
            return (Criteria) this;
        }

        public Criteria andServerMergeidIsNotNull() {
            addCriterion("server_mergeid is not null");
            return (Criteria) this;
        }

        public Criteria andServerMergeidEqualTo(Integer value) {
            addCriterion("server_mergeid =", value, "serverMergeid");
            return (Criteria) this;
        }

        public Criteria andServerMergeidNotEqualTo(Integer value) {
            addCriterion("server_mergeid <>", value, "serverMergeid");
            return (Criteria) this;
        }

        public Criteria andServerMergeidGreaterThan(Integer value) {
            addCriterion("server_mergeid >", value, "serverMergeid");
            return (Criteria) this;
        }

        public Criteria andServerMergeidGreaterThanOrEqualTo(Integer value) {
            addCriterion("server_mergeid >=", value, "serverMergeid");
            return (Criteria) this;
        }

        public Criteria andServerMergeidLessThan(Integer value) {
            addCriterion("server_mergeid <", value, "serverMergeid");
            return (Criteria) this;
        }

        public Criteria andServerMergeidLessThanOrEqualTo(Integer value) {
            addCriterion("server_mergeid <=", value, "serverMergeid");
            return (Criteria) this;
        }

        public Criteria andServerMergeidIn(List<Integer> values) {
            addCriterion("server_mergeid in", values, "serverMergeid");
            return (Criteria) this;
        }

        public Criteria andServerMergeidNotIn(List<Integer> values) {
            addCriterion("server_mergeid not in", values, "serverMergeid");
            return (Criteria) this;
        }

        public Criteria andServerMergeidBetween(Integer value1, Integer value2) {
            addCriterion("server_mergeid between", value1, value2, "serverMergeid");
            return (Criteria) this;
        }

        public Criteria andServerMergeidNotBetween(Integer value1, Integer value2) {
            addCriterion("server_mergeid not between", value1, value2, "serverMergeid");
            return (Criteria) this;
        }

        public Criteria andServerIsregistIsNull() {
            addCriterion("server_isregist is null");
            return (Criteria) this;
        }

        public Criteria andServerIsregistIsNotNull() {
            addCriterion("server_isregist is not null");
            return (Criteria) this;
        }

        public Criteria andServerIsregistEqualTo(Integer value) {
            addCriterion("server_isregist =", value, "serverIsregist");
            return (Criteria) this;
        }

        public Criteria andServerIsregistNotEqualTo(Integer value) {
            addCriterion("server_isregist <>", value, "serverIsregist");
            return (Criteria) this;
        }

        public Criteria andServerIsregistGreaterThan(Integer value) {
            addCriterion("server_isregist >", value, "serverIsregist");
            return (Criteria) this;
        }

        public Criteria andServerIsregistGreaterThanOrEqualTo(Integer value) {
            addCriterion("server_isregist >=", value, "serverIsregist");
            return (Criteria) this;
        }

        public Criteria andServerIsregistLessThan(Integer value) {
            addCriterion("server_isregist <", value, "serverIsregist");
            return (Criteria) this;
        }

        public Criteria andServerIsregistLessThanOrEqualTo(Integer value) {
            addCriterion("server_isregist <=", value, "serverIsregist");
            return (Criteria) this;
        }

        public Criteria andServerIsregistIn(List<Integer> values) {
            addCriterion("server_isregist in", values, "serverIsregist");
            return (Criteria) this;
        }

        public Criteria andServerIsregistNotIn(List<Integer> values) {
            addCriterion("server_isregist not in", values, "serverIsregist");
            return (Criteria) this;
        }

        public Criteria andServerIsregistBetween(Integer value1, Integer value2) {
            addCriterion("server_isregist between", value1, value2, "serverIsregist");
            return (Criteria) this;
        }

        public Criteria andServerIsregistNotBetween(Integer value1, Integer value2) {
            addCriterion("server_isregist not between", value1, value2, "serverIsregist");
            return (Criteria) this;
        }

        public Criteria andServerDbTypeIsNull() {
            addCriterion("server_db_type is null");
            return (Criteria) this;
        }

        public Criteria andServerDbTypeIsNotNull() {
            addCriterion("server_db_type is not null");
            return (Criteria) this;
        }

        public Criteria andServerDbTypeEqualTo(Integer value) {
            addCriterion("server_db_type =", value, "serverDbType");
            return (Criteria) this;
        }

        public Criteria andServerDbTypeNotEqualTo(Integer value) {
            addCriterion("server_db_type <>", value, "serverDbType");
            return (Criteria) this;
        }

        public Criteria andServerDbTypeGreaterThan(Integer value) {
            addCriterion("server_db_type >", value, "serverDbType");
            return (Criteria) this;
        }

        public Criteria andServerDbTypeGreaterThanOrEqualTo(Integer value) {
            addCriterion("server_db_type >=", value, "serverDbType");
            return (Criteria) this;
        }

        public Criteria andServerDbTypeLessThan(Integer value) {
            addCriterion("server_db_type <", value, "serverDbType");
            return (Criteria) this;
        }

        public Criteria andServerDbTypeLessThanOrEqualTo(Integer value) {
            addCriterion("server_db_type <=", value, "serverDbType");
            return (Criteria) this;
        }

        public Criteria andServerDbTypeIn(List<Integer> values) {
            addCriterion("server_db_type in", values, "serverDbType");
            return (Criteria) this;
        }

        public Criteria andServerDbTypeNotIn(List<Integer> values) {
            addCriterion("server_db_type not in", values, "serverDbType");
            return (Criteria) this;
        }

        public Criteria andServerDbTypeBetween(Integer value1, Integer value2) {
            addCriterion("server_db_type between", value1, value2, "serverDbType");
            return (Criteria) this;
        }

        public Criteria andServerDbTypeNotBetween(Integer value1, Integer value2) {
            addCriterion("server_db_type not between", value1, value2, "serverDbType");
            return (Criteria) this;
        }

        public Criteria andServerUrlIsNull() {
            addCriterion("server_url is null");
            return (Criteria) this;
        }

        public Criteria andServerUrlIsNotNull() {
            addCriterion("server_url is not null");
            return (Criteria) this;
        }

        public Criteria andServerUrlEqualTo(String value) {
            addCriterion("server_url =", value, "serverUrl");
            return (Criteria) this;
        }

        public Criteria andServerUrlNotEqualTo(String value) {
            addCriterion("server_url <>", value, "serverUrl");
            return (Criteria) this;
        }

        public Criteria andServerUrlGreaterThan(String value) {
            addCriterion("server_url >", value, "serverUrl");
            return (Criteria) this;
        }

        public Criteria andServerUrlGreaterThanOrEqualTo(String value) {
            addCriterion("server_url >=", value, "serverUrl");
            return (Criteria) this;
        }

        public Criteria andServerUrlLessThan(String value) {
            addCriterion("server_url <", value, "serverUrl");
            return (Criteria) this;
        }

        public Criteria andServerUrlLessThanOrEqualTo(String value) {
            addCriterion("server_url <=", value, "serverUrl");
            return (Criteria) this;
        }

        public Criteria andServerUrlLike(String value) {
            addCriterion("server_url like", value, "serverUrl");
            return (Criteria) this;
        }

        public Criteria andServerUrlNotLike(String value) {
            addCriterion("server_url not like", value, "serverUrl");
            return (Criteria) this;
        }

        public Criteria andServerUrlIn(List<String> values) {
            addCriterion("server_url in", values, "serverUrl");
            return (Criteria) this;
        }

        public Criteria andServerUrlNotIn(List<String> values) {
            addCriterion("server_url not in", values, "serverUrl");
            return (Criteria) this;
        }

        public Criteria andServerUrlBetween(String value1, String value2) {
            addCriterion("server_url between", value1, value2, "serverUrl");
            return (Criteria) this;
        }

        public Criteria andServerUrlNotBetween(String value1, String value2) {
            addCriterion("server_url not between", value1, value2, "serverUrl");
            return (Criteria) this;
        }

        public Criteria andServerUsernameIsNull() {
            addCriterion("server_username is null");
            return (Criteria) this;
        }

        public Criteria andServerUsernameIsNotNull() {
            addCriterion("server_username is not null");
            return (Criteria) this;
        }

        public Criteria andServerUsernameEqualTo(String value) {
            addCriterion("server_username =", value, "serverUsername");
            return (Criteria) this;
        }

        public Criteria andServerUsernameNotEqualTo(String value) {
            addCriterion("server_username <>", value, "serverUsername");
            return (Criteria) this;
        }

        public Criteria andServerUsernameGreaterThan(String value) {
            addCriterion("server_username >", value, "serverUsername");
            return (Criteria) this;
        }

        public Criteria andServerUsernameGreaterThanOrEqualTo(String value) {
            addCriterion("server_username >=", value, "serverUsername");
            return (Criteria) this;
        }

        public Criteria andServerUsernameLessThan(String value) {
            addCriterion("server_username <", value, "serverUsername");
            return (Criteria) this;
        }

        public Criteria andServerUsernameLessThanOrEqualTo(String value) {
            addCriterion("server_username <=", value, "serverUsername");
            return (Criteria) this;
        }

        public Criteria andServerUsernameLike(String value) {
            addCriterion("server_username like", value, "serverUsername");
            return (Criteria) this;
        }

        public Criteria andServerUsernameNotLike(String value) {
            addCriterion("server_username not like", value, "serverUsername");
            return (Criteria) this;
        }

        public Criteria andServerUsernameIn(List<String> values) {
            addCriterion("server_username in", values, "serverUsername");
            return (Criteria) this;
        }

        public Criteria andServerUsernameNotIn(List<String> values) {
            addCriterion("server_username not in", values, "serverUsername");
            return (Criteria) this;
        }

        public Criteria andServerUsernameBetween(String value1, String value2) {
            addCriterion("server_username between", value1, value2, "serverUsername");
            return (Criteria) this;
        }

        public Criteria andServerUsernameNotBetween(String value1, String value2) {
            addCriterion("server_username not between", value1, value2, "serverUsername");
            return (Criteria) this;
        }

        public Criteria andServerPwdIsNull() {
            addCriterion("server_pwd is null");
            return (Criteria) this;
        }

        public Criteria andServerPwdIsNotNull() {
            addCriterion("server_pwd is not null");
            return (Criteria) this;
        }

        public Criteria andServerPwdEqualTo(String value) {
            addCriterion("server_pwd =", value, "serverPwd");
            return (Criteria) this;
        }

        public Criteria andServerPwdNotEqualTo(String value) {
            addCriterion("server_pwd <>", value, "serverPwd");
            return (Criteria) this;
        }

        public Criteria andServerPwdGreaterThan(String value) {
            addCriterion("server_pwd >", value, "serverPwd");
            return (Criteria) this;
        }

        public Criteria andServerPwdGreaterThanOrEqualTo(String value) {
            addCriterion("server_pwd >=", value, "serverPwd");
            return (Criteria) this;
        }

        public Criteria andServerPwdLessThan(String value) {
            addCriterion("server_pwd <", value, "serverPwd");
            return (Criteria) this;
        }

        public Criteria andServerPwdLessThanOrEqualTo(String value) {
            addCriterion("server_pwd <=", value, "serverPwd");
            return (Criteria) this;
        }

        public Criteria andServerPwdLike(String value) {
            addCriterion("server_pwd like", value, "serverPwd");
            return (Criteria) this;
        }

        public Criteria andServerPwdNotLike(String value) {
            addCriterion("server_pwd not like", value, "serverPwd");
            return (Criteria) this;
        }

        public Criteria andServerPwdIn(List<String> values) {
            addCriterion("server_pwd in", values, "serverPwd");
            return (Criteria) this;
        }

        public Criteria andServerPwdNotIn(List<String> values) {
            addCriterion("server_pwd not in", values, "serverPwd");
            return (Criteria) this;
        }

        public Criteria andServerPwdBetween(String value1, String value2) {
            addCriterion("server_pwd between", value1, value2, "serverPwd");
            return (Criteria) this;
        }

        public Criteria andServerPwdNotBetween(String value1, String value2) {
            addCriterion("server_pwd not between", value1, value2, "serverPwd");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table game_server
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table game_server
     *
     * @mbggenerated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}