package com.rs.ocp.domain.endity;

import java.util.Date;

public class GameLogin {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column game_login.login_id
     *
     * @mbggenerated
     */
    private Integer loginId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column game_login.login_userid
     *
     * @mbggenerated
     */
    private Integer loginUserid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column game_login.login_gameid
     *
     * @mbggenerated
     */
    private Integer loginGameid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column game_login.login_areaid
     *
     * @mbggenerated
     */
    private Integer loginAreaid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column game_login.login_serverid
     *
     * @mbggenerated
     */
    private Integer loginServerid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column game_login.login_time
     *
     * @mbggenerated
     */
    private Date loginTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column game_login.login_type
     *
     * @mbggenerated
     */
    private Integer loginType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column game_login.login_sessionid
     *
     * @mbggenerated
     */
    private Integer loginSessionid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column game_login.login_clientip
     *
     * @mbggenerated
     */
    private String loginClientip;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column game_login.login_clientport
     *
     * @mbggenerated
     */
    private Integer loginClientport;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column game_login.login_id
     *
     * @return the value of game_login.login_id
     *
     * @mbggenerated
     */
    public Integer getLoginId() {
        return loginId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column game_login.login_id
     *
     * @param loginId the value for game_login.login_id
     *
     * @mbggenerated
     */
    public void setLoginId(Integer loginId) {
        this.loginId = loginId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column game_login.login_userid
     *
     * @return the value of game_login.login_userid
     *
     * @mbggenerated
     */
    public Integer getLoginUserid() {
        return loginUserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column game_login.login_userid
     *
     * @param loginUserid the value for game_login.login_userid
     *
     * @mbggenerated
     */
    public void setLoginUserid(Integer loginUserid) {
        this.loginUserid = loginUserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column game_login.login_gameid
     *
     * @return the value of game_login.login_gameid
     *
     * @mbggenerated
     */
    public Integer getLoginGameid() {
        return loginGameid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column game_login.login_gameid
     *
     * @param loginGameid the value for game_login.login_gameid
     *
     * @mbggenerated
     */
    public void setLoginGameid(Integer loginGameid) {
        this.loginGameid = loginGameid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column game_login.login_areaid
     *
     * @return the value of game_login.login_areaid
     *
     * @mbggenerated
     */
    public Integer getLoginAreaid() {
        return loginAreaid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column game_login.login_areaid
     *
     * @param loginAreaid the value for game_login.login_areaid
     *
     * @mbggenerated
     */
    public void setLoginAreaid(Integer loginAreaid) {
        this.loginAreaid = loginAreaid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column game_login.login_serverid
     *
     * @return the value of game_login.login_serverid
     *
     * @mbggenerated
     */
    public Integer getLoginServerid() {
        return loginServerid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column game_login.login_serverid
     *
     * @param loginServerid the value for game_login.login_serverid
     *
     * @mbggenerated
     */
    public void setLoginServerid(Integer loginServerid) {
        this.loginServerid = loginServerid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column game_login.login_time
     *
     * @return the value of game_login.login_time
     *
     * @mbggenerated
     */
    public Date getLoginTime() {
        return loginTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column game_login.login_time
     *
     * @param loginTime the value for game_login.login_time
     *
     * @mbggenerated
     */
    public void setLoginTime(Date loginTime) {
        this.loginTime = loginTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column game_login.login_type
     *
     * @return the value of game_login.login_type
     *
     * @mbggenerated
     */
    public Integer getLoginType() {
        return loginType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column game_login.login_type
     *
     * @param loginType the value for game_login.login_type
     *
     * @mbggenerated
     */
    public void setLoginType(Integer loginType) {
        this.loginType = loginType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column game_login.login_sessionid
     *
     * @return the value of game_login.login_sessionid
     *
     * @mbggenerated
     */
    public Integer getLoginSessionid() {
        return loginSessionid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column game_login.login_sessionid
     *
     * @param loginSessionid the value for game_login.login_sessionid
     *
     * @mbggenerated
     */
    public void setLoginSessionid(Integer loginSessionid) {
        this.loginSessionid = loginSessionid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column game_login.login_clientip
     *
     * @return the value of game_login.login_clientip
     *
     * @mbggenerated
     */
    public String getLoginClientip() {
        return loginClientip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column game_login.login_clientip
     *
     * @param loginClientip the value for game_login.login_clientip
     *
     * @mbggenerated
     */
    public void setLoginClientip(String loginClientip) {
        this.loginClientip = loginClientip == null ? null : loginClientip.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column game_login.login_clientport
     *
     * @return the value of game_login.login_clientport
     *
     * @mbggenerated
     */
    public Integer getLoginClientport() {
        return loginClientport;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column game_login.login_clientport
     *
     * @param loginClientport the value for game_login.login_clientport
     *
     * @mbggenerated
     */
    public void setLoginClientport(Integer loginClientport) {
        this.loginClientport = loginClientport;
    }
}