package com.rs.ocp.domain.endity;

import java.util.Date;

public class GameServerLog {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column game_server_log.log_id
     *
     * @mbggenerated
     */
    private Integer logId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column game_server_log.log_serverid
     *
     * @mbggenerated
     */
    private Integer logServerid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column game_server_log.log_type
     *
     * @mbggenerated
     */
    private Integer logType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column game_server_log.log_time
     *
     * @mbggenerated
     */
    private Date logTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column game_server_log.log_remark
     *
     * @mbggenerated
     */
    private String logRemark;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column game_server_log.log_id
     *
     * @return the value of game_server_log.log_id
     *
     * @mbggenerated
     */
    public Integer getLogId() {
        return logId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column game_server_log.log_id
     *
     * @param logId the value for game_server_log.log_id
     *
     * @mbggenerated
     */
    public void setLogId(Integer logId) {
        this.logId = logId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column game_server_log.log_serverid
     *
     * @return the value of game_server_log.log_serverid
     *
     * @mbggenerated
     */
    public Integer getLogServerid() {
        return logServerid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column game_server_log.log_serverid
     *
     * @param logServerid the value for game_server_log.log_serverid
     *
     * @mbggenerated
     */
    public void setLogServerid(Integer logServerid) {
        this.logServerid = logServerid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column game_server_log.log_type
     *
     * @return the value of game_server_log.log_type
     *
     * @mbggenerated
     */
    public Integer getLogType() {
        return logType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column game_server_log.log_type
     *
     * @param logType the value for game_server_log.log_type
     *
     * @mbggenerated
     */
    public void setLogType(Integer logType) {
        this.logType = logType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column game_server_log.log_time
     *
     * @return the value of game_server_log.log_time
     *
     * @mbggenerated
     */
    public Date getLogTime() {
        return logTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column game_server_log.log_time
     *
     * @param logTime the value for game_server_log.log_time
     *
     * @mbggenerated
     */
    public void setLogTime(Date logTime) {
        this.logTime = logTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column game_server_log.log_remark
     *
     * @return the value of game_server_log.log_remark
     *
     * @mbggenerated
     */
    public String getLogRemark() {
        return logRemark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column game_server_log.log_remark
     *
     * @param logRemark the value for game_server_log.log_remark
     *
     * @mbggenerated
     */
    public void setLogRemark(String logRemark) {
        this.logRemark = logRemark == null ? null : logRemark.trim();
    }
}