package com.rs.ocp.domain.endity;

public class GameServer {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column game_server.server_id
     *
     * @mbggenerated
     */
    private Integer serverId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column game_server.server_name
     *
     * @mbggenerated
     */
    private String serverName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column game_server.server_ip
     *
     * @mbggenerated
     */
    private String serverIp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column game_server.server_areaid
     *
     * @mbggenerated
     */
    private Integer serverAreaid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column game_server.server_gameid
     *
     * @mbggenerated
     */
    private Integer serverGameid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column game_server.server_status
     *
     * @mbggenerated
     */
    private Integer serverStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column game_server.server_opentime
     *
     * @mbggenerated
     */
    private Integer serverOpentime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column game_server.server_mergeid
     *
     * @mbggenerated
     */
    private Integer serverMergeid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column game_server.server_isregist
     *
     * @mbggenerated
     */
    private Integer serverIsregist;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column game_server.server_db_type
     *
     * @mbggenerated
     */
    private Integer serverDbType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column game_server.server_url
     *
     * @mbggenerated
     */
    private String serverUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column game_server.server_username
     *
     * @mbggenerated
     */
    private String serverUsername;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column game_server.server_pwd
     *
     * @mbggenerated
     */
    private String serverPwd;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column game_server.server_id
     *
     * @return the value of game_server.server_id
     *
     * @mbggenerated
     */
    public Integer getServerId() {
        return serverId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column game_server.server_id
     *
     * @param serverId the value for game_server.server_id
     *
     * @mbggenerated
     */
    public void setServerId(Integer serverId) {
        this.serverId = serverId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column game_server.server_name
     *
     * @return the value of game_server.server_name
     *
     * @mbggenerated
     */
    public String getServerName() {
        return serverName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column game_server.server_name
     *
     * @param serverName the value for game_server.server_name
     *
     * @mbggenerated
     */
    public void setServerName(String serverName) {
        this.serverName = serverName == null ? null : serverName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column game_server.server_ip
     *
     * @return the value of game_server.server_ip
     *
     * @mbggenerated
     */
    public String getServerIp() {
        return serverIp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column game_server.server_ip
     *
     * @param serverIp the value for game_server.server_ip
     *
     * @mbggenerated
     */
    public void setServerIp(String serverIp) {
        this.serverIp = serverIp == null ? null : serverIp.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column game_server.server_areaid
     *
     * @return the value of game_server.server_areaid
     *
     * @mbggenerated
     */
    public Integer getServerAreaid() {
        return serverAreaid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column game_server.server_areaid
     *
     * @param serverAreaid the value for game_server.server_areaid
     *
     * @mbggenerated
     */
    public void setServerAreaid(Integer serverAreaid) {
        this.serverAreaid = serverAreaid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column game_server.server_gameid
     *
     * @return the value of game_server.server_gameid
     *
     * @mbggenerated
     */
    public Integer getServerGameid() {
        return serverGameid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column game_server.server_gameid
     *
     * @param serverGameid the value for game_server.server_gameid
     *
     * @mbggenerated
     */
    public void setServerGameid(Integer serverGameid) {
        this.serverGameid = serverGameid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column game_server.server_status
     *
     * @return the value of game_server.server_status
     *
     * @mbggenerated
     */
    public Integer getServerStatus() {
        return serverStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column game_server.server_status
     *
     * @param serverStatus the value for game_server.server_status
     *
     * @mbggenerated
     */
    public void setServerStatus(Integer serverStatus) {
        this.serverStatus = serverStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column game_server.server_opentime
     *
     * @return the value of game_server.server_opentime
     *
     * @mbggenerated
     */
    public Integer getServerOpentime() {
        return serverOpentime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column game_server.server_opentime
     *
     * @param serverOpentime the value for game_server.server_opentime
     *
     * @mbggenerated
     */
    public void setServerOpentime(Integer serverOpentime) {
        this.serverOpentime = serverOpentime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column game_server.server_mergeid
     *
     * @return the value of game_server.server_mergeid
     *
     * @mbggenerated
     */
    public Integer getServerMergeid() {
        return serverMergeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column game_server.server_mergeid
     *
     * @param serverMergeid the value for game_server.server_mergeid
     *
     * @mbggenerated
     */
    public void setServerMergeid(Integer serverMergeid) {
        this.serverMergeid = serverMergeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column game_server.server_isregist
     *
     * @return the value of game_server.server_isregist
     *
     * @mbggenerated
     */
    public Integer getServerIsregist() {
        return serverIsregist;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column game_server.server_isregist
     *
     * @param serverIsregist the value for game_server.server_isregist
     *
     * @mbggenerated
     */
    public void setServerIsregist(Integer serverIsregist) {
        this.serverIsregist = serverIsregist;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column game_server.server_db_type
     *
     * @return the value of game_server.server_db_type
     *
     * @mbggenerated
     */
    public Integer getServerDbType() {
        return serverDbType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column game_server.server_db_type
     *
     * @param serverDbType the value for game_server.server_db_type
     *
     * @mbggenerated
     */
    public void setServerDbType(Integer serverDbType) {
        this.serverDbType = serverDbType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column game_server.server_url
     *
     * @return the value of game_server.server_url
     *
     * @mbggenerated
     */
    public String getServerUrl() {
        return serverUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column game_server.server_url
     *
     * @param serverUrl the value for game_server.server_url
     *
     * @mbggenerated
     */
    public void setServerUrl(String serverUrl) {
        this.serverUrl = serverUrl == null ? null : serverUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column game_server.server_username
     *
     * @return the value of game_server.server_username
     *
     * @mbggenerated
     */
    public String getServerUsername() {
        return serverUsername;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column game_server.server_username
     *
     * @param serverUsername the value for game_server.server_username
     *
     * @mbggenerated
     */
    public void setServerUsername(String serverUsername) {
        this.serverUsername = serverUsername == null ? null : serverUsername.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column game_server.server_pwd
     *
     * @return the value of game_server.server_pwd
     *
     * @mbggenerated
     */
    public String getServerPwd() {
        return serverPwd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column game_server.server_pwd
     *
     * @param serverPwd the value for game_server.server_pwd
     *
     * @mbggenerated
     */
    public void setServerPwd(String serverPwd) {
        this.serverPwd = serverPwd == null ? null : serverPwd.trim();
    }
}