package com.rs.ocp.domain.endity;

import java.util.Date;

public class GameRole {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column game_role.role_id
     *
     * @mbggenerated
     */
    private Integer roleId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column game_role.role_pid
     *
     * @mbggenerated
     */
    private Integer rolePid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column game_role.role_gameid
     *
     * @mbggenerated
     */
    private Integer roleGameid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column game_role.role_areaid
     *
     * @mbggenerated
     */
    private Integer roleAreaid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column game_role.role_serverid
     *
     * @mbggenerated
     */
    private Integer roleServerid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column game_role.role_gid
     *
     * @mbggenerated
     */
    private String roleGid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column game_role.role_name
     *
     * @mbggenerated
     */
    private String roleName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column game_role.role_career
     *
     * @mbggenerated
     */
    private String roleCareer;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column game_role.role_sex
     *
     * @mbggenerated
     */
    private String roleSex;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column game_role.role_level
     *
     * @mbggenerated
     */
    private Integer roleLevel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column game_role.role_gold
     *
     * @mbggenerated
     */
    private Integer roleGold;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column game_role.role_unionid
     *
     * @mbggenerated
     */
    private String roleUnionid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column game_role.role_unionname
     *
     * @mbggenerated
     */
    private String roleUnionname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column game_role.role_img
     *
     * @mbggenerated
     */
    private String roleImg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column game_role.role_icon
     *
     * @mbggenerated
     */
    private String roleIcon;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column game_role.role_createtime
     *
     * @mbggenerated
     */
    private Date roleCreatetime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column game_role.role_modifytime
     *
     * @mbggenerated
     */
    private Date roleModifytime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column game_role.role_id
     *
     * @return the value of game_role.role_id
     *
     * @mbggenerated
     */
    public Integer getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column game_role.role_id
     *
     * @param roleId the value for game_role.role_id
     *
     * @mbggenerated
     */
    public void setRoleId(Integer roleId) {
        this.roleId = roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column game_role.role_pid
     *
     * @return the value of game_role.role_pid
     *
     * @mbggenerated
     */
    public Integer getRolePid() {
        return rolePid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column game_role.role_pid
     *
     * @param rolePid the value for game_role.role_pid
     *
     * @mbggenerated
     */
    public void setRolePid(Integer rolePid) {
        this.rolePid = rolePid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column game_role.role_gameid
     *
     * @return the value of game_role.role_gameid
     *
     * @mbggenerated
     */
    public Integer getRoleGameid() {
        return roleGameid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column game_role.role_gameid
     *
     * @param roleGameid the value for game_role.role_gameid
     *
     * @mbggenerated
     */
    public void setRoleGameid(Integer roleGameid) {
        this.roleGameid = roleGameid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column game_role.role_areaid
     *
     * @return the value of game_role.role_areaid
     *
     * @mbggenerated
     */
    public Integer getRoleAreaid() {
        return roleAreaid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column game_role.role_areaid
     *
     * @param roleAreaid the value for game_role.role_areaid
     *
     * @mbggenerated
     */
    public void setRoleAreaid(Integer roleAreaid) {
        this.roleAreaid = roleAreaid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column game_role.role_serverid
     *
     * @return the value of game_role.role_serverid
     *
     * @mbggenerated
     */
    public Integer getRoleServerid() {
        return roleServerid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column game_role.role_serverid
     *
     * @param roleServerid the value for game_role.role_serverid
     *
     * @mbggenerated
     */
    public void setRoleServerid(Integer roleServerid) {
        this.roleServerid = roleServerid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column game_role.role_gid
     *
     * @return the value of game_role.role_gid
     *
     * @mbggenerated
     */
    public String getRoleGid() {
        return roleGid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column game_role.role_gid
     *
     * @param roleGid the value for game_role.role_gid
     *
     * @mbggenerated
     */
    public void setRoleGid(String roleGid) {
        this.roleGid = roleGid == null ? null : roleGid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column game_role.role_name
     *
     * @return the value of game_role.role_name
     *
     * @mbggenerated
     */
    public String getRoleName() {
        return roleName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column game_role.role_name
     *
     * @param roleName the value for game_role.role_name
     *
     * @mbggenerated
     */
    public void setRoleName(String roleName) {
        this.roleName = roleName == null ? null : roleName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column game_role.role_career
     *
     * @return the value of game_role.role_career
     *
     * @mbggenerated
     */
    public String getRoleCareer() {
        return roleCareer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column game_role.role_career
     *
     * @param roleCareer the value for game_role.role_career
     *
     * @mbggenerated
     */
    public void setRoleCareer(String roleCareer) {
        this.roleCareer = roleCareer == null ? null : roleCareer.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column game_role.role_sex
     *
     * @return the value of game_role.role_sex
     *
     * @mbggenerated
     */
    public String getRoleSex() {
        return roleSex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column game_role.role_sex
     *
     * @param roleSex the value for game_role.role_sex
     *
     * @mbggenerated
     */
    public void setRoleSex(String roleSex) {
        this.roleSex = roleSex == null ? null : roleSex.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column game_role.role_level
     *
     * @return the value of game_role.role_level
     *
     * @mbggenerated
     */
    public Integer getRoleLevel() {
        return roleLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column game_role.role_level
     *
     * @param roleLevel the value for game_role.role_level
     *
     * @mbggenerated
     */
    public void setRoleLevel(Integer roleLevel) {
        this.roleLevel = roleLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column game_role.role_gold
     *
     * @return the value of game_role.role_gold
     *
     * @mbggenerated
     */
    public Integer getRoleGold() {
        return roleGold;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column game_role.role_gold
     *
     * @param roleGold the value for game_role.role_gold
     *
     * @mbggenerated
     */
    public void setRoleGold(Integer roleGold) {
        this.roleGold = roleGold;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column game_role.role_unionid
     *
     * @return the value of game_role.role_unionid
     *
     * @mbggenerated
     */
    public String getRoleUnionid() {
        return roleUnionid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column game_role.role_unionid
     *
     * @param roleUnionid the value for game_role.role_unionid
     *
     * @mbggenerated
     */
    public void setRoleUnionid(String roleUnionid) {
        this.roleUnionid = roleUnionid == null ? null : roleUnionid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column game_role.role_unionname
     *
     * @return the value of game_role.role_unionname
     *
     * @mbggenerated
     */
    public String getRoleUnionname() {
        return roleUnionname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column game_role.role_unionname
     *
     * @param roleUnionname the value for game_role.role_unionname
     *
     * @mbggenerated
     */
    public void setRoleUnionname(String roleUnionname) {
        this.roleUnionname = roleUnionname == null ? null : roleUnionname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column game_role.role_img
     *
     * @return the value of game_role.role_img
     *
     * @mbggenerated
     */
    public String getRoleImg() {
        return roleImg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column game_role.role_img
     *
     * @param roleImg the value for game_role.role_img
     *
     * @mbggenerated
     */
    public void setRoleImg(String roleImg) {
        this.roleImg = roleImg == null ? null : roleImg.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column game_role.role_icon
     *
     * @return the value of game_role.role_icon
     *
     * @mbggenerated
     */
    public String getRoleIcon() {
        return roleIcon;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column game_role.role_icon
     *
     * @param roleIcon the value for game_role.role_icon
     *
     * @mbggenerated
     */
    public void setRoleIcon(String roleIcon) {
        this.roleIcon = roleIcon == null ? null : roleIcon.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column game_role.role_createtime
     *
     * @return the value of game_role.role_createtime
     *
     * @mbggenerated
     */
    public Date getRoleCreatetime() {
        return roleCreatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column game_role.role_createtime
     *
     * @param roleCreatetime the value for game_role.role_createtime
     *
     * @mbggenerated
     */
    public void setRoleCreatetime(Date roleCreatetime) {
        this.roleCreatetime = roleCreatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column game_role.role_modifytime
     *
     * @return the value of game_role.role_modifytime
     *
     * @mbggenerated
     */
    public Date getRoleModifytime() {
        return roleModifytime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column game_role.role_modifytime
     *
     * @param roleModifytime the value for game_role.role_modifytime
     *
     * @mbggenerated
     */
    public void setRoleModifytime(Date roleModifytime) {
        this.roleModifytime = roleModifytime;
    }
}