package com.rs.ocp.domain.endity;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class GameRoleExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table game_role
     *
     * @mbggenerated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table game_role
     *
     * @mbggenerated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table game_role
     *
     * @mbggenerated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table game_role
     *
     * @mbggenerated
     */
    public GameRoleExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table game_role
     *
     * @mbggenerated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table game_role
     *
     * @mbggenerated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table game_role
     *
     * @mbggenerated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table game_role
     *
     * @mbggenerated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table game_role
     *
     * @mbggenerated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table game_role
     *
     * @mbggenerated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table game_role
     *
     * @mbggenerated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table game_role
     *
     * @mbggenerated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table game_role
     *
     * @mbggenerated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table game_role
     *
     * @mbggenerated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table game_role
     *
     * @mbggenerated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andRoleIdIsNull() {
            addCriterion("role_id is null");
            return (Criteria) this;
        }

        public Criteria andRoleIdIsNotNull() {
            addCriterion("role_id is not null");
            return (Criteria) this;
        }

        public Criteria andRoleIdEqualTo(Integer value) {
            addCriterion("role_id =", value, "roleId");
            return (Criteria) this;
        }

        public Criteria andRoleIdNotEqualTo(Integer value) {
            addCriterion("role_id <>", value, "roleId");
            return (Criteria) this;
        }

        public Criteria andRoleIdGreaterThan(Integer value) {
            addCriterion("role_id >", value, "roleId");
            return (Criteria) this;
        }

        public Criteria andRoleIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("role_id >=", value, "roleId");
            return (Criteria) this;
        }

        public Criteria andRoleIdLessThan(Integer value) {
            addCriterion("role_id <", value, "roleId");
            return (Criteria) this;
        }

        public Criteria andRoleIdLessThanOrEqualTo(Integer value) {
            addCriterion("role_id <=", value, "roleId");
            return (Criteria) this;
        }

        public Criteria andRoleIdIn(List<Integer> values) {
            addCriterion("role_id in", values, "roleId");
            return (Criteria) this;
        }

        public Criteria andRoleIdNotIn(List<Integer> values) {
            addCriterion("role_id not in", values, "roleId");
            return (Criteria) this;
        }

        public Criteria andRoleIdBetween(Integer value1, Integer value2) {
            addCriterion("role_id between", value1, value2, "roleId");
            return (Criteria) this;
        }

        public Criteria andRoleIdNotBetween(Integer value1, Integer value2) {
            addCriterion("role_id not between", value1, value2, "roleId");
            return (Criteria) this;
        }

        public Criteria andRolePidIsNull() {
            addCriterion("role_pid is null");
            return (Criteria) this;
        }

        public Criteria andRolePidIsNotNull() {
            addCriterion("role_pid is not null");
            return (Criteria) this;
        }

        public Criteria andRolePidEqualTo(Integer value) {
            addCriterion("role_pid =", value, "rolePid");
            return (Criteria) this;
        }

        public Criteria andRolePidNotEqualTo(Integer value) {
            addCriterion("role_pid <>", value, "rolePid");
            return (Criteria) this;
        }

        public Criteria andRolePidGreaterThan(Integer value) {
            addCriterion("role_pid >", value, "rolePid");
            return (Criteria) this;
        }

        public Criteria andRolePidGreaterThanOrEqualTo(Integer value) {
            addCriterion("role_pid >=", value, "rolePid");
            return (Criteria) this;
        }

        public Criteria andRolePidLessThan(Integer value) {
            addCriterion("role_pid <", value, "rolePid");
            return (Criteria) this;
        }

        public Criteria andRolePidLessThanOrEqualTo(Integer value) {
            addCriterion("role_pid <=", value, "rolePid");
            return (Criteria) this;
        }

        public Criteria andRolePidIn(List<Integer> values) {
            addCriterion("role_pid in", values, "rolePid");
            return (Criteria) this;
        }

        public Criteria andRolePidNotIn(List<Integer> values) {
            addCriterion("role_pid not in", values, "rolePid");
            return (Criteria) this;
        }

        public Criteria andRolePidBetween(Integer value1, Integer value2) {
            addCriterion("role_pid between", value1, value2, "rolePid");
            return (Criteria) this;
        }

        public Criteria andRolePidNotBetween(Integer value1, Integer value2) {
            addCriterion("role_pid not between", value1, value2, "rolePid");
            return (Criteria) this;
        }

        public Criteria andRoleGameidIsNull() {
            addCriterion("role_gameid is null");
            return (Criteria) this;
        }

        public Criteria andRoleGameidIsNotNull() {
            addCriterion("role_gameid is not null");
            return (Criteria) this;
        }

        public Criteria andRoleGameidEqualTo(Integer value) {
            addCriterion("role_gameid =", value, "roleGameid");
            return (Criteria) this;
        }

        public Criteria andRoleGameidNotEqualTo(Integer value) {
            addCriterion("role_gameid <>", value, "roleGameid");
            return (Criteria) this;
        }

        public Criteria andRoleGameidGreaterThan(Integer value) {
            addCriterion("role_gameid >", value, "roleGameid");
            return (Criteria) this;
        }

        public Criteria andRoleGameidGreaterThanOrEqualTo(Integer value) {
            addCriterion("role_gameid >=", value, "roleGameid");
            return (Criteria) this;
        }

        public Criteria andRoleGameidLessThan(Integer value) {
            addCriterion("role_gameid <", value, "roleGameid");
            return (Criteria) this;
        }

        public Criteria andRoleGameidLessThanOrEqualTo(Integer value) {
            addCriterion("role_gameid <=", value, "roleGameid");
            return (Criteria) this;
        }

        public Criteria andRoleGameidIn(List<Integer> values) {
            addCriterion("role_gameid in", values, "roleGameid");
            return (Criteria) this;
        }

        public Criteria andRoleGameidNotIn(List<Integer> values) {
            addCriterion("role_gameid not in", values, "roleGameid");
            return (Criteria) this;
        }

        public Criteria andRoleGameidBetween(Integer value1, Integer value2) {
            addCriterion("role_gameid between", value1, value2, "roleGameid");
            return (Criteria) this;
        }

        public Criteria andRoleGameidNotBetween(Integer value1, Integer value2) {
            addCriterion("role_gameid not between", value1, value2, "roleGameid");
            return (Criteria) this;
        }

        public Criteria andRoleAreaidIsNull() {
            addCriterion("role_areaid is null");
            return (Criteria) this;
        }

        public Criteria andRoleAreaidIsNotNull() {
            addCriterion("role_areaid is not null");
            return (Criteria) this;
        }

        public Criteria andRoleAreaidEqualTo(Integer value) {
            addCriterion("role_areaid =", value, "roleAreaid");
            return (Criteria) this;
        }

        public Criteria andRoleAreaidNotEqualTo(Integer value) {
            addCriterion("role_areaid <>", value, "roleAreaid");
            return (Criteria) this;
        }

        public Criteria andRoleAreaidGreaterThan(Integer value) {
            addCriterion("role_areaid >", value, "roleAreaid");
            return (Criteria) this;
        }

        public Criteria andRoleAreaidGreaterThanOrEqualTo(Integer value) {
            addCriterion("role_areaid >=", value, "roleAreaid");
            return (Criteria) this;
        }

        public Criteria andRoleAreaidLessThan(Integer value) {
            addCriterion("role_areaid <", value, "roleAreaid");
            return (Criteria) this;
        }

        public Criteria andRoleAreaidLessThanOrEqualTo(Integer value) {
            addCriterion("role_areaid <=", value, "roleAreaid");
            return (Criteria) this;
        }

        public Criteria andRoleAreaidIn(List<Integer> values) {
            addCriterion("role_areaid in", values, "roleAreaid");
            return (Criteria) this;
        }

        public Criteria andRoleAreaidNotIn(List<Integer> values) {
            addCriterion("role_areaid not in", values, "roleAreaid");
            return (Criteria) this;
        }

        public Criteria andRoleAreaidBetween(Integer value1, Integer value2) {
            addCriterion("role_areaid between", value1, value2, "roleAreaid");
            return (Criteria) this;
        }

        public Criteria andRoleAreaidNotBetween(Integer value1, Integer value2) {
            addCriterion("role_areaid not between", value1, value2, "roleAreaid");
            return (Criteria) this;
        }

        public Criteria andRoleServeridIsNull() {
            addCriterion("role_serverid is null");
            return (Criteria) this;
        }

        public Criteria andRoleServeridIsNotNull() {
            addCriterion("role_serverid is not null");
            return (Criteria) this;
        }

        public Criteria andRoleServeridEqualTo(Integer value) {
            addCriterion("role_serverid =", value, "roleServerid");
            return (Criteria) this;
        }

        public Criteria andRoleServeridNotEqualTo(Integer value) {
            addCriterion("role_serverid <>", value, "roleServerid");
            return (Criteria) this;
        }

        public Criteria andRoleServeridGreaterThan(Integer value) {
            addCriterion("role_serverid >", value, "roleServerid");
            return (Criteria) this;
        }

        public Criteria andRoleServeridGreaterThanOrEqualTo(Integer value) {
            addCriterion("role_serverid >=", value, "roleServerid");
            return (Criteria) this;
        }

        public Criteria andRoleServeridLessThan(Integer value) {
            addCriterion("role_serverid <", value, "roleServerid");
            return (Criteria) this;
        }

        public Criteria andRoleServeridLessThanOrEqualTo(Integer value) {
            addCriterion("role_serverid <=", value, "roleServerid");
            return (Criteria) this;
        }

        public Criteria andRoleServeridIn(List<Integer> values) {
            addCriterion("role_serverid in", values, "roleServerid");
            return (Criteria) this;
        }

        public Criteria andRoleServeridNotIn(List<Integer> values) {
            addCriterion("role_serverid not in", values, "roleServerid");
            return (Criteria) this;
        }

        public Criteria andRoleServeridBetween(Integer value1, Integer value2) {
            addCriterion("role_serverid between", value1, value2, "roleServerid");
            return (Criteria) this;
        }

        public Criteria andRoleServeridNotBetween(Integer value1, Integer value2) {
            addCriterion("role_serverid not between", value1, value2, "roleServerid");
            return (Criteria) this;
        }

        public Criteria andRoleGidIsNull() {
            addCriterion("role_gid is null");
            return (Criteria) this;
        }

        public Criteria andRoleGidIsNotNull() {
            addCriterion("role_gid is not null");
            return (Criteria) this;
        }

        public Criteria andRoleGidEqualTo(String value) {
            addCriterion("role_gid =", value, "roleGid");
            return (Criteria) this;
        }

        public Criteria andRoleGidNotEqualTo(String value) {
            addCriterion("role_gid <>", value, "roleGid");
            return (Criteria) this;
        }

        public Criteria andRoleGidGreaterThan(String value) {
            addCriterion("role_gid >", value, "roleGid");
            return (Criteria) this;
        }

        public Criteria andRoleGidGreaterThanOrEqualTo(String value) {
            addCriterion("role_gid >=", value, "roleGid");
            return (Criteria) this;
        }

        public Criteria andRoleGidLessThan(String value) {
            addCriterion("role_gid <", value, "roleGid");
            return (Criteria) this;
        }

        public Criteria andRoleGidLessThanOrEqualTo(String value) {
            addCriterion("role_gid <=", value, "roleGid");
            return (Criteria) this;
        }

        public Criteria andRoleGidLike(String value) {
            addCriterion("role_gid like", value, "roleGid");
            return (Criteria) this;
        }

        public Criteria andRoleGidNotLike(String value) {
            addCriterion("role_gid not like", value, "roleGid");
            return (Criteria) this;
        }

        public Criteria andRoleGidIn(List<String> values) {
            addCriterion("role_gid in", values, "roleGid");
            return (Criteria) this;
        }

        public Criteria andRoleGidNotIn(List<String> values) {
            addCriterion("role_gid not in", values, "roleGid");
            return (Criteria) this;
        }

        public Criteria andRoleGidBetween(String value1, String value2) {
            addCriterion("role_gid between", value1, value2, "roleGid");
            return (Criteria) this;
        }

        public Criteria andRoleGidNotBetween(String value1, String value2) {
            addCriterion("role_gid not between", value1, value2, "roleGid");
            return (Criteria) this;
        }

        public Criteria andRoleNameIsNull() {
            addCriterion("role_name is null");
            return (Criteria) this;
        }

        public Criteria andRoleNameIsNotNull() {
            addCriterion("role_name is not null");
            return (Criteria) this;
        }

        public Criteria andRoleNameEqualTo(String value) {
            addCriterion("role_name =", value, "roleName");
            return (Criteria) this;
        }

        public Criteria andRoleNameNotEqualTo(String value) {
            addCriterion("role_name <>", value, "roleName");
            return (Criteria) this;
        }

        public Criteria andRoleNameGreaterThan(String value) {
            addCriterion("role_name >", value, "roleName");
            return (Criteria) this;
        }

        public Criteria andRoleNameGreaterThanOrEqualTo(String value) {
            addCriterion("role_name >=", value, "roleName");
            return (Criteria) this;
        }

        public Criteria andRoleNameLessThan(String value) {
            addCriterion("role_name <", value, "roleName");
            return (Criteria) this;
        }

        public Criteria andRoleNameLessThanOrEqualTo(String value) {
            addCriterion("role_name <=", value, "roleName");
            return (Criteria) this;
        }

        public Criteria andRoleNameLike(String value) {
            addCriterion("role_name like", value, "roleName");
            return (Criteria) this;
        }

        public Criteria andRoleNameNotLike(String value) {
            addCriterion("role_name not like", value, "roleName");
            return (Criteria) this;
        }

        public Criteria andRoleNameIn(List<String> values) {
            addCriterion("role_name in", values, "roleName");
            return (Criteria) this;
        }

        public Criteria andRoleNameNotIn(List<String> values) {
            addCriterion("role_name not in", values, "roleName");
            return (Criteria) this;
        }

        public Criteria andRoleNameBetween(String value1, String value2) {
            addCriterion("role_name between", value1, value2, "roleName");
            return (Criteria) this;
        }

        public Criteria andRoleNameNotBetween(String value1, String value2) {
            addCriterion("role_name not between", value1, value2, "roleName");
            return (Criteria) this;
        }

        public Criteria andRoleCareerIsNull() {
            addCriterion("role_career is null");
            return (Criteria) this;
        }

        public Criteria andRoleCareerIsNotNull() {
            addCriterion("role_career is not null");
            return (Criteria) this;
        }

        public Criteria andRoleCareerEqualTo(String value) {
            addCriterion("role_career =", value, "roleCareer");
            return (Criteria) this;
        }

        public Criteria andRoleCareerNotEqualTo(String value) {
            addCriterion("role_career <>", value, "roleCareer");
            return (Criteria) this;
        }

        public Criteria andRoleCareerGreaterThan(String value) {
            addCriterion("role_career >", value, "roleCareer");
            return (Criteria) this;
        }

        public Criteria andRoleCareerGreaterThanOrEqualTo(String value) {
            addCriterion("role_career >=", value, "roleCareer");
            return (Criteria) this;
        }

        public Criteria andRoleCareerLessThan(String value) {
            addCriterion("role_career <", value, "roleCareer");
            return (Criteria) this;
        }

        public Criteria andRoleCareerLessThanOrEqualTo(String value) {
            addCriterion("role_career <=", value, "roleCareer");
            return (Criteria) this;
        }

        public Criteria andRoleCareerLike(String value) {
            addCriterion("role_career like", value, "roleCareer");
            return (Criteria) this;
        }

        public Criteria andRoleCareerNotLike(String value) {
            addCriterion("role_career not like", value, "roleCareer");
            return (Criteria) this;
        }

        public Criteria andRoleCareerIn(List<String> values) {
            addCriterion("role_career in", values, "roleCareer");
            return (Criteria) this;
        }

        public Criteria andRoleCareerNotIn(List<String> values) {
            addCriterion("role_career not in", values, "roleCareer");
            return (Criteria) this;
        }

        public Criteria andRoleCareerBetween(String value1, String value2) {
            addCriterion("role_career between", value1, value2, "roleCareer");
            return (Criteria) this;
        }

        public Criteria andRoleCareerNotBetween(String value1, String value2) {
            addCriterion("role_career not between", value1, value2, "roleCareer");
            return (Criteria) this;
        }

        public Criteria andRoleSexIsNull() {
            addCriterion("role_sex is null");
            return (Criteria) this;
        }

        public Criteria andRoleSexIsNotNull() {
            addCriterion("role_sex is not null");
            return (Criteria) this;
        }

        public Criteria andRoleSexEqualTo(String value) {
            addCriterion("role_sex =", value, "roleSex");
            return (Criteria) this;
        }

        public Criteria andRoleSexNotEqualTo(String value) {
            addCriterion("role_sex <>", value, "roleSex");
            return (Criteria) this;
        }

        public Criteria andRoleSexGreaterThan(String value) {
            addCriterion("role_sex >", value, "roleSex");
            return (Criteria) this;
        }

        public Criteria andRoleSexGreaterThanOrEqualTo(String value) {
            addCriterion("role_sex >=", value, "roleSex");
            return (Criteria) this;
        }

        public Criteria andRoleSexLessThan(String value) {
            addCriterion("role_sex <", value, "roleSex");
            return (Criteria) this;
        }

        public Criteria andRoleSexLessThanOrEqualTo(String value) {
            addCriterion("role_sex <=", value, "roleSex");
            return (Criteria) this;
        }

        public Criteria andRoleSexLike(String value) {
            addCriterion("role_sex like", value, "roleSex");
            return (Criteria) this;
        }

        public Criteria andRoleSexNotLike(String value) {
            addCriterion("role_sex not like", value, "roleSex");
            return (Criteria) this;
        }

        public Criteria andRoleSexIn(List<String> values) {
            addCriterion("role_sex in", values, "roleSex");
            return (Criteria) this;
        }

        public Criteria andRoleSexNotIn(List<String> values) {
            addCriterion("role_sex not in", values, "roleSex");
            return (Criteria) this;
        }

        public Criteria andRoleSexBetween(String value1, String value2) {
            addCriterion("role_sex between", value1, value2, "roleSex");
            return (Criteria) this;
        }

        public Criteria andRoleSexNotBetween(String value1, String value2) {
            addCriterion("role_sex not between", value1, value2, "roleSex");
            return (Criteria) this;
        }

        public Criteria andRoleLevelIsNull() {
            addCriterion("role_level is null");
            return (Criteria) this;
        }

        public Criteria andRoleLevelIsNotNull() {
            addCriterion("role_level is not null");
            return (Criteria) this;
        }

        public Criteria andRoleLevelEqualTo(Integer value) {
            addCriterion("role_level =", value, "roleLevel");
            return (Criteria) this;
        }

        public Criteria andRoleLevelNotEqualTo(Integer value) {
            addCriterion("role_level <>", value, "roleLevel");
            return (Criteria) this;
        }

        public Criteria andRoleLevelGreaterThan(Integer value) {
            addCriterion("role_level >", value, "roleLevel");
            return (Criteria) this;
        }

        public Criteria andRoleLevelGreaterThanOrEqualTo(Integer value) {
            addCriterion("role_level >=", value, "roleLevel");
            return (Criteria) this;
        }

        public Criteria andRoleLevelLessThan(Integer value) {
            addCriterion("role_level <", value, "roleLevel");
            return (Criteria) this;
        }

        public Criteria andRoleLevelLessThanOrEqualTo(Integer value) {
            addCriterion("role_level <=", value, "roleLevel");
            return (Criteria) this;
        }

        public Criteria andRoleLevelIn(List<Integer> values) {
            addCriterion("role_level in", values, "roleLevel");
            return (Criteria) this;
        }

        public Criteria andRoleLevelNotIn(List<Integer> values) {
            addCriterion("role_level not in", values, "roleLevel");
            return (Criteria) this;
        }

        public Criteria andRoleLevelBetween(Integer value1, Integer value2) {
            addCriterion("role_level between", value1, value2, "roleLevel");
            return (Criteria) this;
        }

        public Criteria andRoleLevelNotBetween(Integer value1, Integer value2) {
            addCriterion("role_level not between", value1, value2, "roleLevel");
            return (Criteria) this;
        }

        public Criteria andRoleGoldIsNull() {
            addCriterion("role_gold is null");
            return (Criteria) this;
        }

        public Criteria andRoleGoldIsNotNull() {
            addCriterion("role_gold is not null");
            return (Criteria) this;
        }

        public Criteria andRoleGoldEqualTo(Integer value) {
            addCriterion("role_gold =", value, "roleGold");
            return (Criteria) this;
        }

        public Criteria andRoleGoldNotEqualTo(Integer value) {
            addCriterion("role_gold <>", value, "roleGold");
            return (Criteria) this;
        }

        public Criteria andRoleGoldGreaterThan(Integer value) {
            addCriterion("role_gold >", value, "roleGold");
            return (Criteria) this;
        }

        public Criteria andRoleGoldGreaterThanOrEqualTo(Integer value) {
            addCriterion("role_gold >=", value, "roleGold");
            return (Criteria) this;
        }

        public Criteria andRoleGoldLessThan(Integer value) {
            addCriterion("role_gold <", value, "roleGold");
            return (Criteria) this;
        }

        public Criteria andRoleGoldLessThanOrEqualTo(Integer value) {
            addCriterion("role_gold <=", value, "roleGold");
            return (Criteria) this;
        }

        public Criteria andRoleGoldIn(List<Integer> values) {
            addCriterion("role_gold in", values, "roleGold");
            return (Criteria) this;
        }

        public Criteria andRoleGoldNotIn(List<Integer> values) {
            addCriterion("role_gold not in", values, "roleGold");
            return (Criteria) this;
        }

        public Criteria andRoleGoldBetween(Integer value1, Integer value2) {
            addCriterion("role_gold between", value1, value2, "roleGold");
            return (Criteria) this;
        }

        public Criteria andRoleGoldNotBetween(Integer value1, Integer value2) {
            addCriterion("role_gold not between", value1, value2, "roleGold");
            return (Criteria) this;
        }

        public Criteria andRoleUnionidIsNull() {
            addCriterion("role_unionid is null");
            return (Criteria) this;
        }

        public Criteria andRoleUnionidIsNotNull() {
            addCriterion("role_unionid is not null");
            return (Criteria) this;
        }

        public Criteria andRoleUnionidEqualTo(String value) {
            addCriterion("role_unionid =", value, "roleUnionid");
            return (Criteria) this;
        }

        public Criteria andRoleUnionidNotEqualTo(String value) {
            addCriterion("role_unionid <>", value, "roleUnionid");
            return (Criteria) this;
        }

        public Criteria andRoleUnionidGreaterThan(String value) {
            addCriterion("role_unionid >", value, "roleUnionid");
            return (Criteria) this;
        }

        public Criteria andRoleUnionidGreaterThanOrEqualTo(String value) {
            addCriterion("role_unionid >=", value, "roleUnionid");
            return (Criteria) this;
        }

        public Criteria andRoleUnionidLessThan(String value) {
            addCriterion("role_unionid <", value, "roleUnionid");
            return (Criteria) this;
        }

        public Criteria andRoleUnionidLessThanOrEqualTo(String value) {
            addCriterion("role_unionid <=", value, "roleUnionid");
            return (Criteria) this;
        }

        public Criteria andRoleUnionidLike(String value) {
            addCriterion("role_unionid like", value, "roleUnionid");
            return (Criteria) this;
        }

        public Criteria andRoleUnionidNotLike(String value) {
            addCriterion("role_unionid not like", value, "roleUnionid");
            return (Criteria) this;
        }

        public Criteria andRoleUnionidIn(List<String> values) {
            addCriterion("role_unionid in", values, "roleUnionid");
            return (Criteria) this;
        }

        public Criteria andRoleUnionidNotIn(List<String> values) {
            addCriterion("role_unionid not in", values, "roleUnionid");
            return (Criteria) this;
        }

        public Criteria andRoleUnionidBetween(String value1, String value2) {
            addCriterion("role_unionid between", value1, value2, "roleUnionid");
            return (Criteria) this;
        }

        public Criteria andRoleUnionidNotBetween(String value1, String value2) {
            addCriterion("role_unionid not between", value1, value2, "roleUnionid");
            return (Criteria) this;
        }

        public Criteria andRoleUnionnameIsNull() {
            addCriterion("role_unionname is null");
            return (Criteria) this;
        }

        public Criteria andRoleUnionnameIsNotNull() {
            addCriterion("role_unionname is not null");
            return (Criteria) this;
        }

        public Criteria andRoleUnionnameEqualTo(String value) {
            addCriterion("role_unionname =", value, "roleUnionname");
            return (Criteria) this;
        }

        public Criteria andRoleUnionnameNotEqualTo(String value) {
            addCriterion("role_unionname <>", value, "roleUnionname");
            return (Criteria) this;
        }

        public Criteria andRoleUnionnameGreaterThan(String value) {
            addCriterion("role_unionname >", value, "roleUnionname");
            return (Criteria) this;
        }

        public Criteria andRoleUnionnameGreaterThanOrEqualTo(String value) {
            addCriterion("role_unionname >=", value, "roleUnionname");
            return (Criteria) this;
        }

        public Criteria andRoleUnionnameLessThan(String value) {
            addCriterion("role_unionname <", value, "roleUnionname");
            return (Criteria) this;
        }

        public Criteria andRoleUnionnameLessThanOrEqualTo(String value) {
            addCriterion("role_unionname <=", value, "roleUnionname");
            return (Criteria) this;
        }

        public Criteria andRoleUnionnameLike(String value) {
            addCriterion("role_unionname like", value, "roleUnionname");
            return (Criteria) this;
        }

        public Criteria andRoleUnionnameNotLike(String value) {
            addCriterion("role_unionname not like", value, "roleUnionname");
            return (Criteria) this;
        }

        public Criteria andRoleUnionnameIn(List<String> values) {
            addCriterion("role_unionname in", values, "roleUnionname");
            return (Criteria) this;
        }

        public Criteria andRoleUnionnameNotIn(List<String> values) {
            addCriterion("role_unionname not in", values, "roleUnionname");
            return (Criteria) this;
        }

        public Criteria andRoleUnionnameBetween(String value1, String value2) {
            addCriterion("role_unionname between", value1, value2, "roleUnionname");
            return (Criteria) this;
        }

        public Criteria andRoleUnionnameNotBetween(String value1, String value2) {
            addCriterion("role_unionname not between", value1, value2, "roleUnionname");
            return (Criteria) this;
        }

        public Criteria andRoleImgIsNull() {
            addCriterion("role_img is null");
            return (Criteria) this;
        }

        public Criteria andRoleImgIsNotNull() {
            addCriterion("role_img is not null");
            return (Criteria) this;
        }

        public Criteria andRoleImgEqualTo(String value) {
            addCriterion("role_img =", value, "roleImg");
            return (Criteria) this;
        }

        public Criteria andRoleImgNotEqualTo(String value) {
            addCriterion("role_img <>", value, "roleImg");
            return (Criteria) this;
        }

        public Criteria andRoleImgGreaterThan(String value) {
            addCriterion("role_img >", value, "roleImg");
            return (Criteria) this;
        }

        public Criteria andRoleImgGreaterThanOrEqualTo(String value) {
            addCriterion("role_img >=", value, "roleImg");
            return (Criteria) this;
        }

        public Criteria andRoleImgLessThan(String value) {
            addCriterion("role_img <", value, "roleImg");
            return (Criteria) this;
        }

        public Criteria andRoleImgLessThanOrEqualTo(String value) {
            addCriterion("role_img <=", value, "roleImg");
            return (Criteria) this;
        }

        public Criteria andRoleImgLike(String value) {
            addCriterion("role_img like", value, "roleImg");
            return (Criteria) this;
        }

        public Criteria andRoleImgNotLike(String value) {
            addCriterion("role_img not like", value, "roleImg");
            return (Criteria) this;
        }

        public Criteria andRoleImgIn(List<String> values) {
            addCriterion("role_img in", values, "roleImg");
            return (Criteria) this;
        }

        public Criteria andRoleImgNotIn(List<String> values) {
            addCriterion("role_img not in", values, "roleImg");
            return (Criteria) this;
        }

        public Criteria andRoleImgBetween(String value1, String value2) {
            addCriterion("role_img between", value1, value2, "roleImg");
            return (Criteria) this;
        }

        public Criteria andRoleImgNotBetween(String value1, String value2) {
            addCriterion("role_img not between", value1, value2, "roleImg");
            return (Criteria) this;
        }

        public Criteria andRoleIconIsNull() {
            addCriterion("role_icon is null");
            return (Criteria) this;
        }

        public Criteria andRoleIconIsNotNull() {
            addCriterion("role_icon is not null");
            return (Criteria) this;
        }

        public Criteria andRoleIconEqualTo(String value) {
            addCriterion("role_icon =", value, "roleIcon");
            return (Criteria) this;
        }

        public Criteria andRoleIconNotEqualTo(String value) {
            addCriterion("role_icon <>", value, "roleIcon");
            return (Criteria) this;
        }

        public Criteria andRoleIconGreaterThan(String value) {
            addCriterion("role_icon >", value, "roleIcon");
            return (Criteria) this;
        }

        public Criteria andRoleIconGreaterThanOrEqualTo(String value) {
            addCriterion("role_icon >=", value, "roleIcon");
            return (Criteria) this;
        }

        public Criteria andRoleIconLessThan(String value) {
            addCriterion("role_icon <", value, "roleIcon");
            return (Criteria) this;
        }

        public Criteria andRoleIconLessThanOrEqualTo(String value) {
            addCriterion("role_icon <=", value, "roleIcon");
            return (Criteria) this;
        }

        public Criteria andRoleIconLike(String value) {
            addCriterion("role_icon like", value, "roleIcon");
            return (Criteria) this;
        }

        public Criteria andRoleIconNotLike(String value) {
            addCriterion("role_icon not like", value, "roleIcon");
            return (Criteria) this;
        }

        public Criteria andRoleIconIn(List<String> values) {
            addCriterion("role_icon in", values, "roleIcon");
            return (Criteria) this;
        }

        public Criteria andRoleIconNotIn(List<String> values) {
            addCriterion("role_icon not in", values, "roleIcon");
            return (Criteria) this;
        }

        public Criteria andRoleIconBetween(String value1, String value2) {
            addCriterion("role_icon between", value1, value2, "roleIcon");
            return (Criteria) this;
        }

        public Criteria andRoleIconNotBetween(String value1, String value2) {
            addCriterion("role_icon not between", value1, value2, "roleIcon");
            return (Criteria) this;
        }

        public Criteria andRoleCreatetimeIsNull() {
            addCriterion("role_createtime is null");
            return (Criteria) this;
        }

        public Criteria andRoleCreatetimeIsNotNull() {
            addCriterion("role_createtime is not null");
            return (Criteria) this;
        }

        public Criteria andRoleCreatetimeEqualTo(Date value) {
            addCriterion("role_createtime =", value, "roleCreatetime");
            return (Criteria) this;
        }

        public Criteria andRoleCreatetimeNotEqualTo(Date value) {
            addCriterion("role_createtime <>", value, "roleCreatetime");
            return (Criteria) this;
        }

        public Criteria andRoleCreatetimeGreaterThan(Date value) {
            addCriterion("role_createtime >", value, "roleCreatetime");
            return (Criteria) this;
        }

        public Criteria andRoleCreatetimeGreaterThanOrEqualTo(Date value) {
            addCriterion("role_createtime >=", value, "roleCreatetime");
            return (Criteria) this;
        }

        public Criteria andRoleCreatetimeLessThan(Date value) {
            addCriterion("role_createtime <", value, "roleCreatetime");
            return (Criteria) this;
        }

        public Criteria andRoleCreatetimeLessThanOrEqualTo(Date value) {
            addCriterion("role_createtime <=", value, "roleCreatetime");
            return (Criteria) this;
        }

        public Criteria andRoleCreatetimeIn(List<Date> values) {
            addCriterion("role_createtime in", values, "roleCreatetime");
            return (Criteria) this;
        }

        public Criteria andRoleCreatetimeNotIn(List<Date> values) {
            addCriterion("role_createtime not in", values, "roleCreatetime");
            return (Criteria) this;
        }

        public Criteria andRoleCreatetimeBetween(Date value1, Date value2) {
            addCriterion("role_createtime between", value1, value2, "roleCreatetime");
            return (Criteria) this;
        }

        public Criteria andRoleCreatetimeNotBetween(Date value1, Date value2) {
            addCriterion("role_createtime not between", value1, value2, "roleCreatetime");
            return (Criteria) this;
        }

        public Criteria andRoleModifytimeIsNull() {
            addCriterion("role_modifytime is null");
            return (Criteria) this;
        }

        public Criteria andRoleModifytimeIsNotNull() {
            addCriterion("role_modifytime is not null");
            return (Criteria) this;
        }

        public Criteria andRoleModifytimeEqualTo(Date value) {
            addCriterion("role_modifytime =", value, "roleModifytime");
            return (Criteria) this;
        }

        public Criteria andRoleModifytimeNotEqualTo(Date value) {
            addCriterion("role_modifytime <>", value, "roleModifytime");
            return (Criteria) this;
        }

        public Criteria andRoleModifytimeGreaterThan(Date value) {
            addCriterion("role_modifytime >", value, "roleModifytime");
            return (Criteria) this;
        }

        public Criteria andRoleModifytimeGreaterThanOrEqualTo(Date value) {
            addCriterion("role_modifytime >=", value, "roleModifytime");
            return (Criteria) this;
        }

        public Criteria andRoleModifytimeLessThan(Date value) {
            addCriterion("role_modifytime <", value, "roleModifytime");
            return (Criteria) this;
        }

        public Criteria andRoleModifytimeLessThanOrEqualTo(Date value) {
            addCriterion("role_modifytime <=", value, "roleModifytime");
            return (Criteria) this;
        }

        public Criteria andRoleModifytimeIn(List<Date> values) {
            addCriterion("role_modifytime in", values, "roleModifytime");
            return (Criteria) this;
        }

        public Criteria andRoleModifytimeNotIn(List<Date> values) {
            addCriterion("role_modifytime not in", values, "roleModifytime");
            return (Criteria) this;
        }

        public Criteria andRoleModifytimeBetween(Date value1, Date value2) {
            addCriterion("role_modifytime between", value1, value2, "roleModifytime");
            return (Criteria) this;
        }

        public Criteria andRoleModifytimeNotBetween(Date value1, Date value2) {
            addCriterion("role_modifytime not between", value1, value2, "roleModifytime");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table game_role
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table game_role
     *
     * @mbggenerated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}