package com.rs.ocp.domain.endity;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class PpFcmTotaltimeExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table pp_fcm_totaltime
     *
     * @mbggenerated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table pp_fcm_totaltime
     *
     * @mbggenerated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table pp_fcm_totaltime
     *
     * @mbggenerated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pp_fcm_totaltime
     *
     * @mbggenerated
     */
    public PpFcmTotaltimeExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pp_fcm_totaltime
     *
     * @mbggenerated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pp_fcm_totaltime
     *
     * @mbggenerated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pp_fcm_totaltime
     *
     * @mbggenerated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pp_fcm_totaltime
     *
     * @mbggenerated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pp_fcm_totaltime
     *
     * @mbggenerated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pp_fcm_totaltime
     *
     * @mbggenerated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pp_fcm_totaltime
     *
     * @mbggenerated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pp_fcm_totaltime
     *
     * @mbggenerated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pp_fcm_totaltime
     *
     * @mbggenerated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pp_fcm_totaltime
     *
     * @mbggenerated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table pp_fcm_totaltime
     *
     * @mbggenerated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andFcmIdIsNull() {
            addCriterion("fcm_id is null");
            return (Criteria) this;
        }

        public Criteria andFcmIdIsNotNull() {
            addCriterion("fcm_id is not null");
            return (Criteria) this;
        }

        public Criteria andFcmIdEqualTo(Integer value) {
            addCriterion("fcm_id =", value, "fcmId");
            return (Criteria) this;
        }

        public Criteria andFcmIdNotEqualTo(Integer value) {
            addCriterion("fcm_id <>", value, "fcmId");
            return (Criteria) this;
        }

        public Criteria andFcmIdGreaterThan(Integer value) {
            addCriterion("fcm_id >", value, "fcmId");
            return (Criteria) this;
        }

        public Criteria andFcmIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("fcm_id >=", value, "fcmId");
            return (Criteria) this;
        }

        public Criteria andFcmIdLessThan(Integer value) {
            addCriterion("fcm_id <", value, "fcmId");
            return (Criteria) this;
        }

        public Criteria andFcmIdLessThanOrEqualTo(Integer value) {
            addCriterion("fcm_id <=", value, "fcmId");
            return (Criteria) this;
        }

        public Criteria andFcmIdIn(List<Integer> values) {
            addCriterion("fcm_id in", values, "fcmId");
            return (Criteria) this;
        }

        public Criteria andFcmIdNotIn(List<Integer> values) {
            addCriterion("fcm_id not in", values, "fcmId");
            return (Criteria) this;
        }

        public Criteria andFcmIdBetween(Integer value1, Integer value2) {
            addCriterion("fcm_id between", value1, value2, "fcmId");
            return (Criteria) this;
        }

        public Criteria andFcmIdNotBetween(Integer value1, Integer value2) {
            addCriterion("fcm_id not between", value1, value2, "fcmId");
            return (Criteria) this;
        }

        public Criteria andFcmPidIsNull() {
            addCriterion("fcm_pid is null");
            return (Criteria) this;
        }

        public Criteria andFcmPidIsNotNull() {
            addCriterion("fcm_pid is not null");
            return (Criteria) this;
        }

        public Criteria andFcmPidEqualTo(Integer value) {
            addCriterion("fcm_pid =", value, "fcmPid");
            return (Criteria) this;
        }

        public Criteria andFcmPidNotEqualTo(Integer value) {
            addCriterion("fcm_pid <>", value, "fcmPid");
            return (Criteria) this;
        }

        public Criteria andFcmPidGreaterThan(Integer value) {
            addCriterion("fcm_pid >", value, "fcmPid");
            return (Criteria) this;
        }

        public Criteria andFcmPidGreaterThanOrEqualTo(Integer value) {
            addCriterion("fcm_pid >=", value, "fcmPid");
            return (Criteria) this;
        }

        public Criteria andFcmPidLessThan(Integer value) {
            addCriterion("fcm_pid <", value, "fcmPid");
            return (Criteria) this;
        }

        public Criteria andFcmPidLessThanOrEqualTo(Integer value) {
            addCriterion("fcm_pid <=", value, "fcmPid");
            return (Criteria) this;
        }

        public Criteria andFcmPidIn(List<Integer> values) {
            addCriterion("fcm_pid in", values, "fcmPid");
            return (Criteria) this;
        }

        public Criteria andFcmPidNotIn(List<Integer> values) {
            addCriterion("fcm_pid not in", values, "fcmPid");
            return (Criteria) this;
        }

        public Criteria andFcmPidBetween(Integer value1, Integer value2) {
            addCriterion("fcm_pid between", value1, value2, "fcmPid");
            return (Criteria) this;
        }

        public Criteria andFcmPidNotBetween(Integer value1, Integer value2) {
            addCriterion("fcm_pid not between", value1, value2, "fcmPid");
            return (Criteria) this;
        }

        public Criteria andFcmGameidIsNull() {
            addCriterion("fcm_gameid is null");
            return (Criteria) this;
        }

        public Criteria andFcmGameidIsNotNull() {
            addCriterion("fcm_gameid is not null");
            return (Criteria) this;
        }

        public Criteria andFcmGameidEqualTo(Integer value) {
            addCriterion("fcm_gameid =", value, "fcmGameid");
            return (Criteria) this;
        }

        public Criteria andFcmGameidNotEqualTo(Integer value) {
            addCriterion("fcm_gameid <>", value, "fcmGameid");
            return (Criteria) this;
        }

        public Criteria andFcmGameidGreaterThan(Integer value) {
            addCriterion("fcm_gameid >", value, "fcmGameid");
            return (Criteria) this;
        }

        public Criteria andFcmGameidGreaterThanOrEqualTo(Integer value) {
            addCriterion("fcm_gameid >=", value, "fcmGameid");
            return (Criteria) this;
        }

        public Criteria andFcmGameidLessThan(Integer value) {
            addCriterion("fcm_gameid <", value, "fcmGameid");
            return (Criteria) this;
        }

        public Criteria andFcmGameidLessThanOrEqualTo(Integer value) {
            addCriterion("fcm_gameid <=", value, "fcmGameid");
            return (Criteria) this;
        }

        public Criteria andFcmGameidIn(List<Integer> values) {
            addCriterion("fcm_gameid in", values, "fcmGameid");
            return (Criteria) this;
        }

        public Criteria andFcmGameidNotIn(List<Integer> values) {
            addCriterion("fcm_gameid not in", values, "fcmGameid");
            return (Criteria) this;
        }

        public Criteria andFcmGameidBetween(Integer value1, Integer value2) {
            addCriterion("fcm_gameid between", value1, value2, "fcmGameid");
            return (Criteria) this;
        }

        public Criteria andFcmGameidNotBetween(Integer value1, Integer value2) {
            addCriterion("fcm_gameid not between", value1, value2, "fcmGameid");
            return (Criteria) this;
        }

        public Criteria andFcmOnlinetimeIsNull() {
            addCriterion("fcm_onlinetime is null");
            return (Criteria) this;
        }

        public Criteria andFcmOnlinetimeIsNotNull() {
            addCriterion("fcm_onlinetime is not null");
            return (Criteria) this;
        }

        public Criteria andFcmOnlinetimeEqualTo(Integer value) {
            addCriterion("fcm_onlinetime =", value, "fcmOnlinetime");
            return (Criteria) this;
        }

        public Criteria andFcmOnlinetimeNotEqualTo(Integer value) {
            addCriterion("fcm_onlinetime <>", value, "fcmOnlinetime");
            return (Criteria) this;
        }

        public Criteria andFcmOnlinetimeGreaterThan(Integer value) {
            addCriterion("fcm_onlinetime >", value, "fcmOnlinetime");
            return (Criteria) this;
        }

        public Criteria andFcmOnlinetimeGreaterThanOrEqualTo(Integer value) {
            addCriterion("fcm_onlinetime >=", value, "fcmOnlinetime");
            return (Criteria) this;
        }

        public Criteria andFcmOnlinetimeLessThan(Integer value) {
            addCriterion("fcm_onlinetime <", value, "fcmOnlinetime");
            return (Criteria) this;
        }

        public Criteria andFcmOnlinetimeLessThanOrEqualTo(Integer value) {
            addCriterion("fcm_onlinetime <=", value, "fcmOnlinetime");
            return (Criteria) this;
        }

        public Criteria andFcmOnlinetimeIn(List<Integer> values) {
            addCriterion("fcm_onlinetime in", values, "fcmOnlinetime");
            return (Criteria) this;
        }

        public Criteria andFcmOnlinetimeNotIn(List<Integer> values) {
            addCriterion("fcm_onlinetime not in", values, "fcmOnlinetime");
            return (Criteria) this;
        }

        public Criteria andFcmOnlinetimeBetween(Integer value1, Integer value2) {
            addCriterion("fcm_onlinetime between", value1, value2, "fcmOnlinetime");
            return (Criteria) this;
        }

        public Criteria andFcmOnlinetimeNotBetween(Integer value1, Integer value2) {
            addCriterion("fcm_onlinetime not between", value1, value2, "fcmOnlinetime");
            return (Criteria) this;
        }

        public Criteria andFcmOfflinetimeIsNull() {
            addCriterion("fcm_offlinetime is null");
            return (Criteria) this;
        }

        public Criteria andFcmOfflinetimeIsNotNull() {
            addCriterion("fcm_offlinetime is not null");
            return (Criteria) this;
        }

        public Criteria andFcmOfflinetimeEqualTo(Integer value) {
            addCriterion("fcm_offlinetime =", value, "fcmOfflinetime");
            return (Criteria) this;
        }

        public Criteria andFcmOfflinetimeNotEqualTo(Integer value) {
            addCriterion("fcm_offlinetime <>", value, "fcmOfflinetime");
            return (Criteria) this;
        }

        public Criteria andFcmOfflinetimeGreaterThan(Integer value) {
            addCriterion("fcm_offlinetime >", value, "fcmOfflinetime");
            return (Criteria) this;
        }

        public Criteria andFcmOfflinetimeGreaterThanOrEqualTo(Integer value) {
            addCriterion("fcm_offlinetime >=", value, "fcmOfflinetime");
            return (Criteria) this;
        }

        public Criteria andFcmOfflinetimeLessThan(Integer value) {
            addCriterion("fcm_offlinetime <", value, "fcmOfflinetime");
            return (Criteria) this;
        }

        public Criteria andFcmOfflinetimeLessThanOrEqualTo(Integer value) {
            addCriterion("fcm_offlinetime <=", value, "fcmOfflinetime");
            return (Criteria) this;
        }

        public Criteria andFcmOfflinetimeIn(List<Integer> values) {
            addCriterion("fcm_offlinetime in", values, "fcmOfflinetime");
            return (Criteria) this;
        }

        public Criteria andFcmOfflinetimeNotIn(List<Integer> values) {
            addCriterion("fcm_offlinetime not in", values, "fcmOfflinetime");
            return (Criteria) this;
        }

        public Criteria andFcmOfflinetimeBetween(Integer value1, Integer value2) {
            addCriterion("fcm_offlinetime between", value1, value2, "fcmOfflinetime");
            return (Criteria) this;
        }

        public Criteria andFcmOfflinetimeNotBetween(Integer value1, Integer value2) {
            addCriterion("fcm_offlinetime not between", value1, value2, "fcmOfflinetime");
            return (Criteria) this;
        }

        public Criteria andFcmLogintimeIsNull() {
            addCriterion("fcm_logintime is null");
            return (Criteria) this;
        }

        public Criteria andFcmLogintimeIsNotNull() {
            addCriterion("fcm_logintime is not null");
            return (Criteria) this;
        }

        public Criteria andFcmLogintimeEqualTo(Date value) {
            addCriterion("fcm_logintime =", value, "fcmLogintime");
            return (Criteria) this;
        }

        public Criteria andFcmLogintimeNotEqualTo(Date value) {
            addCriterion("fcm_logintime <>", value, "fcmLogintime");
            return (Criteria) this;
        }

        public Criteria andFcmLogintimeGreaterThan(Date value) {
            addCriterion("fcm_logintime >", value, "fcmLogintime");
            return (Criteria) this;
        }

        public Criteria andFcmLogintimeGreaterThanOrEqualTo(Date value) {
            addCriterion("fcm_logintime >=", value, "fcmLogintime");
            return (Criteria) this;
        }

        public Criteria andFcmLogintimeLessThan(Date value) {
            addCriterion("fcm_logintime <", value, "fcmLogintime");
            return (Criteria) this;
        }

        public Criteria andFcmLogintimeLessThanOrEqualTo(Date value) {
            addCriterion("fcm_logintime <=", value, "fcmLogintime");
            return (Criteria) this;
        }

        public Criteria andFcmLogintimeIn(List<Date> values) {
            addCriterion("fcm_logintime in", values, "fcmLogintime");
            return (Criteria) this;
        }

        public Criteria andFcmLogintimeNotIn(List<Date> values) {
            addCriterion("fcm_logintime not in", values, "fcmLogintime");
            return (Criteria) this;
        }

        public Criteria andFcmLogintimeBetween(Date value1, Date value2) {
            addCriterion("fcm_logintime between", value1, value2, "fcmLogintime");
            return (Criteria) this;
        }

        public Criteria andFcmLogintimeNotBetween(Date value1, Date value2) {
            addCriterion("fcm_logintime not between", value1, value2, "fcmLogintime");
            return (Criteria) this;
        }

        public Criteria andFcmLogouttimeIsNull() {
            addCriterion("fcm_logouttime is null");
            return (Criteria) this;
        }

        public Criteria andFcmLogouttimeIsNotNull() {
            addCriterion("fcm_logouttime is not null");
            return (Criteria) this;
        }

        public Criteria andFcmLogouttimeEqualTo(Date value) {
            addCriterion("fcm_logouttime =", value, "fcmLogouttime");
            return (Criteria) this;
        }

        public Criteria andFcmLogouttimeNotEqualTo(Date value) {
            addCriterion("fcm_logouttime <>", value, "fcmLogouttime");
            return (Criteria) this;
        }

        public Criteria andFcmLogouttimeGreaterThan(Date value) {
            addCriterion("fcm_logouttime >", value, "fcmLogouttime");
            return (Criteria) this;
        }

        public Criteria andFcmLogouttimeGreaterThanOrEqualTo(Date value) {
            addCriterion("fcm_logouttime >=", value, "fcmLogouttime");
            return (Criteria) this;
        }

        public Criteria andFcmLogouttimeLessThan(Date value) {
            addCriterion("fcm_logouttime <", value, "fcmLogouttime");
            return (Criteria) this;
        }

        public Criteria andFcmLogouttimeLessThanOrEqualTo(Date value) {
            addCriterion("fcm_logouttime <=", value, "fcmLogouttime");
            return (Criteria) this;
        }

        public Criteria andFcmLogouttimeIn(List<Date> values) {
            addCriterion("fcm_logouttime in", values, "fcmLogouttime");
            return (Criteria) this;
        }

        public Criteria andFcmLogouttimeNotIn(List<Date> values) {
            addCriterion("fcm_logouttime not in", values, "fcmLogouttime");
            return (Criteria) this;
        }

        public Criteria andFcmLogouttimeBetween(Date value1, Date value2) {
            addCriterion("fcm_logouttime between", value1, value2, "fcmLogouttime");
            return (Criteria) this;
        }

        public Criteria andFcmLogouttimeNotBetween(Date value1, Date value2) {
            addCriterion("fcm_logouttime not between", value1, value2, "fcmLogouttime");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table pp_fcm_totaltime
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table pp_fcm_totaltime
     *
     * @mbggenerated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}