package com.rs.ocp.domain.endity;

public class PpPassport {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pp_passport.passport_pid
     *
     * @mbggenerated
     */
    private Integer passportPid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pp_passport.passport_name
     *
     * @mbggenerated
     */
    private String passportName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pp_passport.passport_email
     *
     * @mbggenerated
     */
    private String passportEmail;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pp_passport.passport_phone
     *
     * @mbggenerated
     */
    private String passportPhone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pp_passport.passport_pwd
     *
     * @mbggenerated
     */
    private String passportPwd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pp_passport.passport_flag
     *
     * @mbggenerated
     */
    private String passportFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pp_passport.passport_identity
     *
     * @mbggenerated
     */
    private String passportIdentity;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pp_passport.passport_gmlevel
     *
     * @mbggenerated
     */
    private String passportGmlevel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pp_passport.passport_status
     *
     * @mbggenerated
     */
    private String passportStatus;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pp_passport.passport_pid
     *
     * @return the value of pp_passport.passport_pid
     *
     * @mbggenerated
     */
    public Integer getPassportPid() {
        return passportPid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pp_passport.passport_pid
     *
     * @param passportPid the value for pp_passport.passport_pid
     *
     * @mbggenerated
     */
    public void setPassportPid(Integer passportPid) {
        this.passportPid = passportPid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pp_passport.passport_name
     *
     * @return the value of pp_passport.passport_name
     *
     * @mbggenerated
     */
    public String getPassportName() {
        return passportName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pp_passport.passport_name
     *
     * @param passportName the value for pp_passport.passport_name
     *
     * @mbggenerated
     */
    public void setPassportName(String passportName) {
        this.passportName = passportName == null ? null : passportName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pp_passport.passport_email
     *
     * @return the value of pp_passport.passport_email
     *
     * @mbggenerated
     */
    public String getPassportEmail() {
        return passportEmail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pp_passport.passport_email
     *
     * @param passportEmail the value for pp_passport.passport_email
     *
     * @mbggenerated
     */
    public void setPassportEmail(String passportEmail) {
        this.passportEmail = passportEmail == null ? null : passportEmail.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pp_passport.passport_phone
     *
     * @return the value of pp_passport.passport_phone
     *
     * @mbggenerated
     */
    public String getPassportPhone() {
        return passportPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pp_passport.passport_phone
     *
     * @param passportPhone the value for pp_passport.passport_phone
     *
     * @mbggenerated
     */
    public void setPassportPhone(String passportPhone) {
        this.passportPhone = passportPhone == null ? null : passportPhone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pp_passport.passport_pwd
     *
     * @return the value of pp_passport.passport_pwd
     *
     * @mbggenerated
     */
    public String getPassportPwd() {
        return passportPwd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pp_passport.passport_pwd
     *
     * @param passportPwd the value for pp_passport.passport_pwd
     *
     * @mbggenerated
     */
    public void setPassportPwd(String passportPwd) {
        this.passportPwd = passportPwd == null ? null : passportPwd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pp_passport.passport_flag
     *
     * @return the value of pp_passport.passport_flag
     *
     * @mbggenerated
     */
    public String getPassportFlag() {
        return passportFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pp_passport.passport_flag
     *
     * @param passportFlag the value for pp_passport.passport_flag
     *
     * @mbggenerated
     */
    public void setPassportFlag(String passportFlag) {
        this.passportFlag = passportFlag == null ? null : passportFlag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pp_passport.passport_identity
     *
     * @return the value of pp_passport.passport_identity
     *
     * @mbggenerated
     */
    public String getPassportIdentity() {
        return passportIdentity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pp_passport.passport_identity
     *
     * @param passportIdentity the value for pp_passport.passport_identity
     *
     * @mbggenerated
     */
    public void setPassportIdentity(String passportIdentity) {
        this.passportIdentity = passportIdentity == null ? null : passportIdentity.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pp_passport.passport_gmlevel
     *
     * @return the value of pp_passport.passport_gmlevel
     *
     * @mbggenerated
     */
    public String getPassportGmlevel() {
        return passportGmlevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pp_passport.passport_gmlevel
     *
     * @param passportGmlevel the value for pp_passport.passport_gmlevel
     *
     * @mbggenerated
     */
    public void setPassportGmlevel(String passportGmlevel) {
        this.passportGmlevel = passportGmlevel == null ? null : passportGmlevel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pp_passport.passport_status
     *
     * @return the value of pp_passport.passport_status
     *
     * @mbggenerated
     */
    public String getPassportStatus() {
        return passportStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pp_passport.passport_status
     *
     * @param passportStatus the value for pp_passport.passport_status
     *
     * @mbggenerated
     */
    public void setPassportStatus(String passportStatus) {
        this.passportStatus = passportStatus == null ? null : passportStatus.trim();
    }
}