package com.rs.ocp.domain.endity;

import java.util.ArrayList;
import java.util.List;

public class PpPassportExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table pp_passport
     *
     * @mbggenerated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table pp_passport
     *
     * @mbggenerated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table pp_passport
     *
     * @mbggenerated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pp_passport
     *
     * @mbggenerated
     */
    public PpPassportExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pp_passport
     *
     * @mbggenerated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pp_passport
     *
     * @mbggenerated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pp_passport
     *
     * @mbggenerated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pp_passport
     *
     * @mbggenerated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pp_passport
     *
     * @mbggenerated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pp_passport
     *
     * @mbggenerated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pp_passport
     *
     * @mbggenerated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pp_passport
     *
     * @mbggenerated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pp_passport
     *
     * @mbggenerated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pp_passport
     *
     * @mbggenerated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table pp_passport
     *
     * @mbggenerated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andPassportPidIsNull() {
            addCriterion("passport_pid is null");
            return (Criteria) this;
        }

        public Criteria andPassportPidIsNotNull() {
            addCriterion("passport_pid is not null");
            return (Criteria) this;
        }

        public Criteria andPassportPidEqualTo(Integer value) {
            addCriterion("passport_pid =", value, "passportPid");
            return (Criteria) this;
        }

        public Criteria andPassportPidNotEqualTo(Integer value) {
            addCriterion("passport_pid <>", value, "passportPid");
            return (Criteria) this;
        }

        public Criteria andPassportPidGreaterThan(Integer value) {
            addCriterion("passport_pid >", value, "passportPid");
            return (Criteria) this;
        }

        public Criteria andPassportPidGreaterThanOrEqualTo(Integer value) {
            addCriterion("passport_pid >=", value, "passportPid");
            return (Criteria) this;
        }

        public Criteria andPassportPidLessThan(Integer value) {
            addCriterion("passport_pid <", value, "passportPid");
            return (Criteria) this;
        }

        public Criteria andPassportPidLessThanOrEqualTo(Integer value) {
            addCriterion("passport_pid <=", value, "passportPid");
            return (Criteria) this;
        }

        public Criteria andPassportPidIn(List<Integer> values) {
            addCriterion("passport_pid in", values, "passportPid");
            return (Criteria) this;
        }

        public Criteria andPassportPidNotIn(List<Integer> values) {
            addCriterion("passport_pid not in", values, "passportPid");
            return (Criteria) this;
        }

        public Criteria andPassportPidBetween(Integer value1, Integer value2) {
            addCriterion("passport_pid between", value1, value2, "passportPid");
            return (Criteria) this;
        }

        public Criteria andPassportPidNotBetween(Integer value1, Integer value2) {
            addCriterion("passport_pid not between", value1, value2, "passportPid");
            return (Criteria) this;
        }

        public Criteria andPassportNameIsNull() {
            addCriterion("passport_name is null");
            return (Criteria) this;
        }

        public Criteria andPassportNameIsNotNull() {
            addCriterion("passport_name is not null");
            return (Criteria) this;
        }

        public Criteria andPassportNameEqualTo(String value) {
            addCriterion("passport_name =", value, "passportName");
            return (Criteria) this;
        }

        public Criteria andPassportNameNotEqualTo(String value) {
            addCriterion("passport_name <>", value, "passportName");
            return (Criteria) this;
        }

        public Criteria andPassportNameGreaterThan(String value) {
            addCriterion("passport_name >", value, "passportName");
            return (Criteria) this;
        }

        public Criteria andPassportNameGreaterThanOrEqualTo(String value) {
            addCriterion("passport_name >=", value, "passportName");
            return (Criteria) this;
        }

        public Criteria andPassportNameLessThan(String value) {
            addCriterion("passport_name <", value, "passportName");
            return (Criteria) this;
        }

        public Criteria andPassportNameLessThanOrEqualTo(String value) {
            addCriterion("passport_name <=", value, "passportName");
            return (Criteria) this;
        }

        public Criteria andPassportNameLike(String value) {
            addCriterion("passport_name like", value, "passportName");
            return (Criteria) this;
        }

        public Criteria andPassportNameNotLike(String value) {
            addCriterion("passport_name not like", value, "passportName");
            return (Criteria) this;
        }

        public Criteria andPassportNameIn(List<String> values) {
            addCriterion("passport_name in", values, "passportName");
            return (Criteria) this;
        }

        public Criteria andPassportNameNotIn(List<String> values) {
            addCriterion("passport_name not in", values, "passportName");
            return (Criteria) this;
        }

        public Criteria andPassportNameBetween(String value1, String value2) {
            addCriterion("passport_name between", value1, value2, "passportName");
            return (Criteria) this;
        }

        public Criteria andPassportNameNotBetween(String value1, String value2) {
            addCriterion("passport_name not between", value1, value2, "passportName");
            return (Criteria) this;
        }

        public Criteria andPassportEmailIsNull() {
            addCriterion("passport_email is null");
            return (Criteria) this;
        }

        public Criteria andPassportEmailIsNotNull() {
            addCriterion("passport_email is not null");
            return (Criteria) this;
        }

        public Criteria andPassportEmailEqualTo(String value) {
            addCriterion("passport_email =", value, "passportEmail");
            return (Criteria) this;
        }

        public Criteria andPassportEmailNotEqualTo(String value) {
            addCriterion("passport_email <>", value, "passportEmail");
            return (Criteria) this;
        }

        public Criteria andPassportEmailGreaterThan(String value) {
            addCriterion("passport_email >", value, "passportEmail");
            return (Criteria) this;
        }

        public Criteria andPassportEmailGreaterThanOrEqualTo(String value) {
            addCriterion("passport_email >=", value, "passportEmail");
            return (Criteria) this;
        }

        public Criteria andPassportEmailLessThan(String value) {
            addCriterion("passport_email <", value, "passportEmail");
            return (Criteria) this;
        }

        public Criteria andPassportEmailLessThanOrEqualTo(String value) {
            addCriterion("passport_email <=", value, "passportEmail");
            return (Criteria) this;
        }

        public Criteria andPassportEmailLike(String value) {
            addCriterion("passport_email like", value, "passportEmail");
            return (Criteria) this;
        }

        public Criteria andPassportEmailNotLike(String value) {
            addCriterion("passport_email not like", value, "passportEmail");
            return (Criteria) this;
        }

        public Criteria andPassportEmailIn(List<String> values) {
            addCriterion("passport_email in", values, "passportEmail");
            return (Criteria) this;
        }

        public Criteria andPassportEmailNotIn(List<String> values) {
            addCriterion("passport_email not in", values, "passportEmail");
            return (Criteria) this;
        }

        public Criteria andPassportEmailBetween(String value1, String value2) {
            addCriterion("passport_email between", value1, value2, "passportEmail");
            return (Criteria) this;
        }

        public Criteria andPassportEmailNotBetween(String value1, String value2) {
            addCriterion("passport_email not between", value1, value2, "passportEmail");
            return (Criteria) this;
        }

        public Criteria andPassportPhoneIsNull() {
            addCriterion("passport_phone is null");
            return (Criteria) this;
        }

        public Criteria andPassportPhoneIsNotNull() {
            addCriterion("passport_phone is not null");
            return (Criteria) this;
        }

        public Criteria andPassportPhoneEqualTo(String value) {
            addCriterion("passport_phone =", value, "passportPhone");
            return (Criteria) this;
        }

        public Criteria andPassportPhoneNotEqualTo(String value) {
            addCriterion("passport_phone <>", value, "passportPhone");
            return (Criteria) this;
        }

        public Criteria andPassportPhoneGreaterThan(String value) {
            addCriterion("passport_phone >", value, "passportPhone");
            return (Criteria) this;
        }

        public Criteria andPassportPhoneGreaterThanOrEqualTo(String value) {
            addCriterion("passport_phone >=", value, "passportPhone");
            return (Criteria) this;
        }

        public Criteria andPassportPhoneLessThan(String value) {
            addCriterion("passport_phone <", value, "passportPhone");
            return (Criteria) this;
        }

        public Criteria andPassportPhoneLessThanOrEqualTo(String value) {
            addCriterion("passport_phone <=", value, "passportPhone");
            return (Criteria) this;
        }

        public Criteria andPassportPhoneLike(String value) {
            addCriterion("passport_phone like", value, "passportPhone");
            return (Criteria) this;
        }

        public Criteria andPassportPhoneNotLike(String value) {
            addCriterion("passport_phone not like", value, "passportPhone");
            return (Criteria) this;
        }

        public Criteria andPassportPhoneIn(List<String> values) {
            addCriterion("passport_phone in", values, "passportPhone");
            return (Criteria) this;
        }

        public Criteria andPassportPhoneNotIn(List<String> values) {
            addCriterion("passport_phone not in", values, "passportPhone");
            return (Criteria) this;
        }

        public Criteria andPassportPhoneBetween(String value1, String value2) {
            addCriterion("passport_phone between", value1, value2, "passportPhone");
            return (Criteria) this;
        }

        public Criteria andPassportPhoneNotBetween(String value1, String value2) {
            addCriterion("passport_phone not between", value1, value2, "passportPhone");
            return (Criteria) this;
        }

        public Criteria andPassportPwdIsNull() {
            addCriterion("passport_pwd is null");
            return (Criteria) this;
        }

        public Criteria andPassportPwdIsNotNull() {
            addCriterion("passport_pwd is not null");
            return (Criteria) this;
        }

        public Criteria andPassportPwdEqualTo(String value) {
            addCriterion("passport_pwd =", value, "passportPwd");
            return (Criteria) this;
        }

        public Criteria andPassportPwdNotEqualTo(String value) {
            addCriterion("passport_pwd <>", value, "passportPwd");
            return (Criteria) this;
        }

        public Criteria andPassportPwdGreaterThan(String value) {
            addCriterion("passport_pwd >", value, "passportPwd");
            return (Criteria) this;
        }

        public Criteria andPassportPwdGreaterThanOrEqualTo(String value) {
            addCriterion("passport_pwd >=", value, "passportPwd");
            return (Criteria) this;
        }

        public Criteria andPassportPwdLessThan(String value) {
            addCriterion("passport_pwd <", value, "passportPwd");
            return (Criteria) this;
        }

        public Criteria andPassportPwdLessThanOrEqualTo(String value) {
            addCriterion("passport_pwd <=", value, "passportPwd");
            return (Criteria) this;
        }

        public Criteria andPassportPwdLike(String value) {
            addCriterion("passport_pwd like", value, "passportPwd");
            return (Criteria) this;
        }

        public Criteria andPassportPwdNotLike(String value) {
            addCriterion("passport_pwd not like", value, "passportPwd");
            return (Criteria) this;
        }

        public Criteria andPassportPwdIn(List<String> values) {
            addCriterion("passport_pwd in", values, "passportPwd");
            return (Criteria) this;
        }

        public Criteria andPassportPwdNotIn(List<String> values) {
            addCriterion("passport_pwd not in", values, "passportPwd");
            return (Criteria) this;
        }

        public Criteria andPassportPwdBetween(String value1, String value2) {
            addCriterion("passport_pwd between", value1, value2, "passportPwd");
            return (Criteria) this;
        }

        public Criteria andPassportPwdNotBetween(String value1, String value2) {
            addCriterion("passport_pwd not between", value1, value2, "passportPwd");
            return (Criteria) this;
        }

        public Criteria andPassportFlagIsNull() {
            addCriterion("passport_flag is null");
            return (Criteria) this;
        }

        public Criteria andPassportFlagIsNotNull() {
            addCriterion("passport_flag is not null");
            return (Criteria) this;
        }

        public Criteria andPassportFlagEqualTo(String value) {
            addCriterion("passport_flag =", value, "passportFlag");
            return (Criteria) this;
        }

        public Criteria andPassportFlagNotEqualTo(String value) {
            addCriterion("passport_flag <>", value, "passportFlag");
            return (Criteria) this;
        }

        public Criteria andPassportFlagGreaterThan(String value) {
            addCriterion("passport_flag >", value, "passportFlag");
            return (Criteria) this;
        }

        public Criteria andPassportFlagGreaterThanOrEqualTo(String value) {
            addCriterion("passport_flag >=", value, "passportFlag");
            return (Criteria) this;
        }

        public Criteria andPassportFlagLessThan(String value) {
            addCriterion("passport_flag <", value, "passportFlag");
            return (Criteria) this;
        }

        public Criteria andPassportFlagLessThanOrEqualTo(String value) {
            addCriterion("passport_flag <=", value, "passportFlag");
            return (Criteria) this;
        }

        public Criteria andPassportFlagLike(String value) {
            addCriterion("passport_flag like", value, "passportFlag");
            return (Criteria) this;
        }

        public Criteria andPassportFlagNotLike(String value) {
            addCriterion("passport_flag not like", value, "passportFlag");
            return (Criteria) this;
        }

        public Criteria andPassportFlagIn(List<String> values) {
            addCriterion("passport_flag in", values, "passportFlag");
            return (Criteria) this;
        }

        public Criteria andPassportFlagNotIn(List<String> values) {
            addCriterion("passport_flag not in", values, "passportFlag");
            return (Criteria) this;
        }

        public Criteria andPassportFlagBetween(String value1, String value2) {
            addCriterion("passport_flag between", value1, value2, "passportFlag");
            return (Criteria) this;
        }

        public Criteria andPassportFlagNotBetween(String value1, String value2) {
            addCriterion("passport_flag not between", value1, value2, "passportFlag");
            return (Criteria) this;
        }

        public Criteria andPassportIdentityIsNull() {
            addCriterion("passport_identity is null");
            return (Criteria) this;
        }

        public Criteria andPassportIdentityIsNotNull() {
            addCriterion("passport_identity is not null");
            return (Criteria) this;
        }

        public Criteria andPassportIdentityEqualTo(String value) {
            addCriterion("passport_identity =", value, "passportIdentity");
            return (Criteria) this;
        }

        public Criteria andPassportIdentityNotEqualTo(String value) {
            addCriterion("passport_identity <>", value, "passportIdentity");
            return (Criteria) this;
        }

        public Criteria andPassportIdentityGreaterThan(String value) {
            addCriterion("passport_identity >", value, "passportIdentity");
            return (Criteria) this;
        }

        public Criteria andPassportIdentityGreaterThanOrEqualTo(String value) {
            addCriterion("passport_identity >=", value, "passportIdentity");
            return (Criteria) this;
        }

        public Criteria andPassportIdentityLessThan(String value) {
            addCriterion("passport_identity <", value, "passportIdentity");
            return (Criteria) this;
        }

        public Criteria andPassportIdentityLessThanOrEqualTo(String value) {
            addCriterion("passport_identity <=", value, "passportIdentity");
            return (Criteria) this;
        }

        public Criteria andPassportIdentityLike(String value) {
            addCriterion("passport_identity like", value, "passportIdentity");
            return (Criteria) this;
        }

        public Criteria andPassportIdentityNotLike(String value) {
            addCriterion("passport_identity not like", value, "passportIdentity");
            return (Criteria) this;
        }

        public Criteria andPassportIdentityIn(List<String> values) {
            addCriterion("passport_identity in", values, "passportIdentity");
            return (Criteria) this;
        }

        public Criteria andPassportIdentityNotIn(List<String> values) {
            addCriterion("passport_identity not in", values, "passportIdentity");
            return (Criteria) this;
        }

        public Criteria andPassportIdentityBetween(String value1, String value2) {
            addCriterion("passport_identity between", value1, value2, "passportIdentity");
            return (Criteria) this;
        }

        public Criteria andPassportIdentityNotBetween(String value1, String value2) {
            addCriterion("passport_identity not between", value1, value2, "passportIdentity");
            return (Criteria) this;
        }

        public Criteria andPassportGmlevelIsNull() {
            addCriterion("passport_gmlevel is null");
            return (Criteria) this;
        }

        public Criteria andPassportGmlevelIsNotNull() {
            addCriterion("passport_gmlevel is not null");
            return (Criteria) this;
        }

        public Criteria andPassportGmlevelEqualTo(String value) {
            addCriterion("passport_gmlevel =", value, "passportGmlevel");
            return (Criteria) this;
        }

        public Criteria andPassportGmlevelNotEqualTo(String value) {
            addCriterion("passport_gmlevel <>", value, "passportGmlevel");
            return (Criteria) this;
        }

        public Criteria andPassportGmlevelGreaterThan(String value) {
            addCriterion("passport_gmlevel >", value, "passportGmlevel");
            return (Criteria) this;
        }

        public Criteria andPassportGmlevelGreaterThanOrEqualTo(String value) {
            addCriterion("passport_gmlevel >=", value, "passportGmlevel");
            return (Criteria) this;
        }

        public Criteria andPassportGmlevelLessThan(String value) {
            addCriterion("passport_gmlevel <", value, "passportGmlevel");
            return (Criteria) this;
        }

        public Criteria andPassportGmlevelLessThanOrEqualTo(String value) {
            addCriterion("passport_gmlevel <=", value, "passportGmlevel");
            return (Criteria) this;
        }

        public Criteria andPassportGmlevelLike(String value) {
            addCriterion("passport_gmlevel like", value, "passportGmlevel");
            return (Criteria) this;
        }

        public Criteria andPassportGmlevelNotLike(String value) {
            addCriterion("passport_gmlevel not like", value, "passportGmlevel");
            return (Criteria) this;
        }

        public Criteria andPassportGmlevelIn(List<String> values) {
            addCriterion("passport_gmlevel in", values, "passportGmlevel");
            return (Criteria) this;
        }

        public Criteria andPassportGmlevelNotIn(List<String> values) {
            addCriterion("passport_gmlevel not in", values, "passportGmlevel");
            return (Criteria) this;
        }

        public Criteria andPassportGmlevelBetween(String value1, String value2) {
            addCriterion("passport_gmlevel between", value1, value2, "passportGmlevel");
            return (Criteria) this;
        }

        public Criteria andPassportGmlevelNotBetween(String value1, String value2) {
            addCriterion("passport_gmlevel not between", value1, value2, "passportGmlevel");
            return (Criteria) this;
        }

        public Criteria andPassportStatusIsNull() {
            addCriterion("passport_status is null");
            return (Criteria) this;
        }

        public Criteria andPassportStatusIsNotNull() {
            addCriterion("passport_status is not null");
            return (Criteria) this;
        }

        public Criteria andPassportStatusEqualTo(String value) {
            addCriterion("passport_status =", value, "passportStatus");
            return (Criteria) this;
        }

        public Criteria andPassportStatusNotEqualTo(String value) {
            addCriterion("passport_status <>", value, "passportStatus");
            return (Criteria) this;
        }

        public Criteria andPassportStatusGreaterThan(String value) {
            addCriterion("passport_status >", value, "passportStatus");
            return (Criteria) this;
        }

        public Criteria andPassportStatusGreaterThanOrEqualTo(String value) {
            addCriterion("passport_status >=", value, "passportStatus");
            return (Criteria) this;
        }

        public Criteria andPassportStatusLessThan(String value) {
            addCriterion("passport_status <", value, "passportStatus");
            return (Criteria) this;
        }

        public Criteria andPassportStatusLessThanOrEqualTo(String value) {
            addCriterion("passport_status <=", value, "passportStatus");
            return (Criteria) this;
        }

        public Criteria andPassportStatusLike(String value) {
            addCriterion("passport_status like", value, "passportStatus");
            return (Criteria) this;
        }

        public Criteria andPassportStatusNotLike(String value) {
            addCriterion("passport_status not like", value, "passportStatus");
            return (Criteria) this;
        }

        public Criteria andPassportStatusIn(List<String> values) {
            addCriterion("passport_status in", values, "passportStatus");
            return (Criteria) this;
        }

        public Criteria andPassportStatusNotIn(List<String> values) {
            addCriterion("passport_status not in", values, "passportStatus");
            return (Criteria) this;
        }

        public Criteria andPassportStatusBetween(String value1, String value2) {
            addCriterion("passport_status between", value1, value2, "passportStatus");
            return (Criteria) this;
        }

        public Criteria andPassportStatusNotBetween(String value1, String value2) {
            addCriterion("passport_status not between", value1, value2, "passportStatus");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table pp_passport
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table pp_passport
     *
     * @mbggenerated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}