package com.rs.ocp.domain.endity;

import java.util.Date;

public class PpStatus {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pp_status.status_pid
     *
     * @mbggenerated
     */
    private Integer statusPid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pp_status.status_type
     *
     * @mbggenerated
     */
    private Integer statusType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pp_status.status_frozenscope
     *
     * @mbggenerated
     */
    private Integer statusFrozenscope;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pp_status.status_frozentime
     *
     * @mbggenerated
     */
    private Date statusFrozentime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pp_status.status_pid
     *
     * @return the value of pp_status.status_pid
     *
     * @mbggenerated
     */
    public Integer getStatusPid() {
        return statusPid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pp_status.status_pid
     *
     * @param statusPid the value for pp_status.status_pid
     *
     * @mbggenerated
     */
    public void setStatusPid(Integer statusPid) {
        this.statusPid = statusPid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pp_status.status_type
     *
     * @return the value of pp_status.status_type
     *
     * @mbggenerated
     */
    public Integer getStatusType() {
        return statusType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pp_status.status_type
     *
     * @param statusType the value for pp_status.status_type
     *
     * @mbggenerated
     */
    public void setStatusType(Integer statusType) {
        this.statusType = statusType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pp_status.status_frozenscope
     *
     * @return the value of pp_status.status_frozenscope
     *
     * @mbggenerated
     */
    public Integer getStatusFrozenscope() {
        return statusFrozenscope;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pp_status.status_frozenscope
     *
     * @param statusFrozenscope the value for pp_status.status_frozenscope
     *
     * @mbggenerated
     */
    public void setStatusFrozenscope(Integer statusFrozenscope) {
        this.statusFrozenscope = statusFrozenscope;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pp_status.status_frozentime
     *
     * @return the value of pp_status.status_frozentime
     *
     * @mbggenerated
     */
    public Date getStatusFrozentime() {
        return statusFrozentime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pp_status.status_frozentime
     *
     * @param statusFrozentime the value for pp_status.status_frozentime
     *
     * @mbggenerated
     */
    public void setStatusFrozentime(Date statusFrozentime) {
        this.statusFrozentime = statusFrozentime;
    }
}