package com.rs.ocp.domain.endity;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class PpStatusExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table pp_status
     *
     * @mbggenerated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table pp_status
     *
     * @mbggenerated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table pp_status
     *
     * @mbggenerated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pp_status
     *
     * @mbggenerated
     */
    public PpStatusExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pp_status
     *
     * @mbggenerated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pp_status
     *
     * @mbggenerated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pp_status
     *
     * @mbggenerated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pp_status
     *
     * @mbggenerated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pp_status
     *
     * @mbggenerated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pp_status
     *
     * @mbggenerated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pp_status
     *
     * @mbggenerated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pp_status
     *
     * @mbggenerated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pp_status
     *
     * @mbggenerated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pp_status
     *
     * @mbggenerated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table pp_status
     *
     * @mbggenerated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andStatusPidIsNull() {
            addCriterion("status_pid is null");
            return (Criteria) this;
        }

        public Criteria andStatusPidIsNotNull() {
            addCriterion("status_pid is not null");
            return (Criteria) this;
        }

        public Criteria andStatusPidEqualTo(Integer value) {
            addCriterion("status_pid =", value, "statusPid");
            return (Criteria) this;
        }

        public Criteria andStatusPidNotEqualTo(Integer value) {
            addCriterion("status_pid <>", value, "statusPid");
            return (Criteria) this;
        }

        public Criteria andStatusPidGreaterThan(Integer value) {
            addCriterion("status_pid >", value, "statusPid");
            return (Criteria) this;
        }

        public Criteria andStatusPidGreaterThanOrEqualTo(Integer value) {
            addCriterion("status_pid >=", value, "statusPid");
            return (Criteria) this;
        }

        public Criteria andStatusPidLessThan(Integer value) {
            addCriterion("status_pid <", value, "statusPid");
            return (Criteria) this;
        }

        public Criteria andStatusPidLessThanOrEqualTo(Integer value) {
            addCriterion("status_pid <=", value, "statusPid");
            return (Criteria) this;
        }

        public Criteria andStatusPidIn(List<Integer> values) {
            addCriterion("status_pid in", values, "statusPid");
            return (Criteria) this;
        }

        public Criteria andStatusPidNotIn(List<Integer> values) {
            addCriterion("status_pid not in", values, "statusPid");
            return (Criteria) this;
        }

        public Criteria andStatusPidBetween(Integer value1, Integer value2) {
            addCriterion("status_pid between", value1, value2, "statusPid");
            return (Criteria) this;
        }

        public Criteria andStatusPidNotBetween(Integer value1, Integer value2) {
            addCriterion("status_pid not between", value1, value2, "statusPid");
            return (Criteria) this;
        }

        public Criteria andStatusTypeIsNull() {
            addCriterion("status_type is null");
            return (Criteria) this;
        }

        public Criteria andStatusTypeIsNotNull() {
            addCriterion("status_type is not null");
            return (Criteria) this;
        }

        public Criteria andStatusTypeEqualTo(Integer value) {
            addCriterion("status_type =", value, "statusType");
            return (Criteria) this;
        }

        public Criteria andStatusTypeNotEqualTo(Integer value) {
            addCriterion("status_type <>", value, "statusType");
            return (Criteria) this;
        }

        public Criteria andStatusTypeGreaterThan(Integer value) {
            addCriterion("status_type >", value, "statusType");
            return (Criteria) this;
        }

        public Criteria andStatusTypeGreaterThanOrEqualTo(Integer value) {
            addCriterion("status_type >=", value, "statusType");
            return (Criteria) this;
        }

        public Criteria andStatusTypeLessThan(Integer value) {
            addCriterion("status_type <", value, "statusType");
            return (Criteria) this;
        }

        public Criteria andStatusTypeLessThanOrEqualTo(Integer value) {
            addCriterion("status_type <=", value, "statusType");
            return (Criteria) this;
        }

        public Criteria andStatusTypeIn(List<Integer> values) {
            addCriterion("status_type in", values, "statusType");
            return (Criteria) this;
        }

        public Criteria andStatusTypeNotIn(List<Integer> values) {
            addCriterion("status_type not in", values, "statusType");
            return (Criteria) this;
        }

        public Criteria andStatusTypeBetween(Integer value1, Integer value2) {
            addCriterion("status_type between", value1, value2, "statusType");
            return (Criteria) this;
        }

        public Criteria andStatusTypeNotBetween(Integer value1, Integer value2) {
            addCriterion("status_type not between", value1, value2, "statusType");
            return (Criteria) this;
        }

        public Criteria andStatusFrozenscopeIsNull() {
            addCriterion("status_frozenscope is null");
            return (Criteria) this;
        }

        public Criteria andStatusFrozenscopeIsNotNull() {
            addCriterion("status_frozenscope is not null");
            return (Criteria) this;
        }

        public Criteria andStatusFrozenscopeEqualTo(Integer value) {
            addCriterion("status_frozenscope =", value, "statusFrozenscope");
            return (Criteria) this;
        }

        public Criteria andStatusFrozenscopeNotEqualTo(Integer value) {
            addCriterion("status_frozenscope <>", value, "statusFrozenscope");
            return (Criteria) this;
        }

        public Criteria andStatusFrozenscopeGreaterThan(Integer value) {
            addCriterion("status_frozenscope >", value, "statusFrozenscope");
            return (Criteria) this;
        }

        public Criteria andStatusFrozenscopeGreaterThanOrEqualTo(Integer value) {
            addCriterion("status_frozenscope >=", value, "statusFrozenscope");
            return (Criteria) this;
        }

        public Criteria andStatusFrozenscopeLessThan(Integer value) {
            addCriterion("status_frozenscope <", value, "statusFrozenscope");
            return (Criteria) this;
        }

        public Criteria andStatusFrozenscopeLessThanOrEqualTo(Integer value) {
            addCriterion("status_frozenscope <=", value, "statusFrozenscope");
            return (Criteria) this;
        }

        public Criteria andStatusFrozenscopeIn(List<Integer> values) {
            addCriterion("status_frozenscope in", values, "statusFrozenscope");
            return (Criteria) this;
        }

        public Criteria andStatusFrozenscopeNotIn(List<Integer> values) {
            addCriterion("status_frozenscope not in", values, "statusFrozenscope");
            return (Criteria) this;
        }

        public Criteria andStatusFrozenscopeBetween(Integer value1, Integer value2) {
            addCriterion("status_frozenscope between", value1, value2, "statusFrozenscope");
            return (Criteria) this;
        }

        public Criteria andStatusFrozenscopeNotBetween(Integer value1, Integer value2) {
            addCriterion("status_frozenscope not between", value1, value2, "statusFrozenscope");
            return (Criteria) this;
        }

        public Criteria andStatusFrozentimeIsNull() {
            addCriterion("status_frozentime is null");
            return (Criteria) this;
        }

        public Criteria andStatusFrozentimeIsNotNull() {
            addCriterion("status_frozentime is not null");
            return (Criteria) this;
        }

        public Criteria andStatusFrozentimeEqualTo(Date value) {
            addCriterion("status_frozentime =", value, "statusFrozentime");
            return (Criteria) this;
        }

        public Criteria andStatusFrozentimeNotEqualTo(Date value) {
            addCriterion("status_frozentime <>", value, "statusFrozentime");
            return (Criteria) this;
        }

        public Criteria andStatusFrozentimeGreaterThan(Date value) {
            addCriterion("status_frozentime >", value, "statusFrozentime");
            return (Criteria) this;
        }

        public Criteria andStatusFrozentimeGreaterThanOrEqualTo(Date value) {
            addCriterion("status_frozentime >=", value, "statusFrozentime");
            return (Criteria) this;
        }

        public Criteria andStatusFrozentimeLessThan(Date value) {
            addCriterion("status_frozentime <", value, "statusFrozentime");
            return (Criteria) this;
        }

        public Criteria andStatusFrozentimeLessThanOrEqualTo(Date value) {
            addCriterion("status_frozentime <=", value, "statusFrozentime");
            return (Criteria) this;
        }

        public Criteria andStatusFrozentimeIn(List<Date> values) {
            addCriterion("status_frozentime in", values, "statusFrozentime");
            return (Criteria) this;
        }

        public Criteria andStatusFrozentimeNotIn(List<Date> values) {
            addCriterion("status_frozentime not in", values, "statusFrozentime");
            return (Criteria) this;
        }

        public Criteria andStatusFrozentimeBetween(Date value1, Date value2) {
            addCriterion("status_frozentime between", value1, value2, "statusFrozentime");
            return (Criteria) this;
        }

        public Criteria andStatusFrozentimeNotBetween(Date value1, Date value2) {
            addCriterion("status_frozentime not between", value1, value2, "statusFrozentime");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table pp_status
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table pp_status
     *
     * @mbggenerated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}