package com.rs.ocp.domain.endity;

public class PpUser {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pp_user.user_pid
     *
     * @mbggenerated
     */
    private Integer userPid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pp_user.user_realname
     *
     * @mbggenerated
     */
    private String userRealname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pp_user.user_idcardnum
     *
     * @mbggenerated
     */
    private String userIdcardnum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pp_user.user_address
     *
     * @mbggenerated
     */
    private String userAddress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pp_user.user_birth
     *
     * @mbggenerated
     */
    private String userBirth;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pp_user.user_income
     *
     * @mbggenerated
     */
    private Integer userIncome;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pp_user.user_profession
     *
     * @mbggenerated
     */
    private Integer userProfession;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pp_user.user_sex
     *
     * @mbggenerated
     */
    private Integer userSex;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pp_user.user_edu
     *
     * @mbggenerated
     */
    private Integer userEdu;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pp_user.user_balance
     *
     * @mbggenerated
     */
    private Integer userBalance;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pp_user.user_time
     *
     * @mbggenerated
     */
    private Integer userTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pp_user.user_lasttime
     *
     * @mbggenerated
     */
    private Integer userLasttime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pp_user.user_pid
     *
     * @return the value of pp_user.user_pid
     *
     * @mbggenerated
     */
    public Integer getUserPid() {
        return userPid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pp_user.user_pid
     *
     * @param userPid the value for pp_user.user_pid
     *
     * @mbggenerated
     */
    public void setUserPid(Integer userPid) {
        this.userPid = userPid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pp_user.user_realname
     *
     * @return the value of pp_user.user_realname
     *
     * @mbggenerated
     */
    public String getUserRealname() {
        return userRealname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pp_user.user_realname
     *
     * @param userRealname the value for pp_user.user_realname
     *
     * @mbggenerated
     */
    public void setUserRealname(String userRealname) {
        this.userRealname = userRealname == null ? null : userRealname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pp_user.user_idcardnum
     *
     * @return the value of pp_user.user_idcardnum
     *
     * @mbggenerated
     */
    public String getUserIdcardnum() {
        return userIdcardnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pp_user.user_idcardnum
     *
     * @param userIdcardnum the value for pp_user.user_idcardnum
     *
     * @mbggenerated
     */
    public void setUserIdcardnum(String userIdcardnum) {
        this.userIdcardnum = userIdcardnum == null ? null : userIdcardnum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pp_user.user_address
     *
     * @return the value of pp_user.user_address
     *
     * @mbggenerated
     */
    public String getUserAddress() {
        return userAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pp_user.user_address
     *
     * @param userAddress the value for pp_user.user_address
     *
     * @mbggenerated
     */
    public void setUserAddress(String userAddress) {
        this.userAddress = userAddress == null ? null : userAddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pp_user.user_birth
     *
     * @return the value of pp_user.user_birth
     *
     * @mbggenerated
     */
    public String getUserBirth() {
        return userBirth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pp_user.user_birth
     *
     * @param userBirth the value for pp_user.user_birth
     *
     * @mbggenerated
     */
    public void setUserBirth(String userBirth) {
        this.userBirth = userBirth == null ? null : userBirth.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pp_user.user_income
     *
     * @return the value of pp_user.user_income
     *
     * @mbggenerated
     */
    public Integer getUserIncome() {
        return userIncome;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pp_user.user_income
     *
     * @param userIncome the value for pp_user.user_income
     *
     * @mbggenerated
     */
    public void setUserIncome(Integer userIncome) {
        this.userIncome = userIncome;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pp_user.user_profession
     *
     * @return the value of pp_user.user_profession
     *
     * @mbggenerated
     */
    public Integer getUserProfession() {
        return userProfession;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pp_user.user_profession
     *
     * @param userProfession the value for pp_user.user_profession
     *
     * @mbggenerated
     */
    public void setUserProfession(Integer userProfession) {
        this.userProfession = userProfession;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pp_user.user_sex
     *
     * @return the value of pp_user.user_sex
     *
     * @mbggenerated
     */
    public Integer getUserSex() {
        return userSex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pp_user.user_sex
     *
     * @param userSex the value for pp_user.user_sex
     *
     * @mbggenerated
     */
    public void setUserSex(Integer userSex) {
        this.userSex = userSex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pp_user.user_edu
     *
     * @return the value of pp_user.user_edu
     *
     * @mbggenerated
     */
    public Integer getUserEdu() {
        return userEdu;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pp_user.user_edu
     *
     * @param userEdu the value for pp_user.user_edu
     *
     * @mbggenerated
     */
    public void setUserEdu(Integer userEdu) {
        this.userEdu = userEdu;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pp_user.user_balance
     *
     * @return the value of pp_user.user_balance
     *
     * @mbggenerated
     */
    public Integer getUserBalance() {
        return userBalance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pp_user.user_balance
     *
     * @param userBalance the value for pp_user.user_balance
     *
     * @mbggenerated
     */
    public void setUserBalance(Integer userBalance) {
        this.userBalance = userBalance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pp_user.user_time
     *
     * @return the value of pp_user.user_time
     *
     * @mbggenerated
     */
    public Integer getUserTime() {
        return userTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pp_user.user_time
     *
     * @param userTime the value for pp_user.user_time
     *
     * @mbggenerated
     */
    public void setUserTime(Integer userTime) {
        this.userTime = userTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pp_user.user_lasttime
     *
     * @return the value of pp_user.user_lasttime
     *
     * @mbggenerated
     */
    public Integer getUserLasttime() {
        return userLasttime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pp_user.user_lasttime
     *
     * @param userLasttime the value for pp_user.user_lasttime
     *
     * @mbggenerated
     */
    public void setUserLasttime(Integer userLasttime) {
        this.userLasttime = userLasttime;
    }
}