package com.rs.ocp.domain.endity;

import java.util.ArrayList;
import java.util.List;

public class PpUserExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table pp_user
     *
     * @mbggenerated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table pp_user
     *
     * @mbggenerated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table pp_user
     *
     * @mbggenerated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pp_user
     *
     * @mbggenerated
     */
    public PpUserExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pp_user
     *
     * @mbggenerated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pp_user
     *
     * @mbggenerated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pp_user
     *
     * @mbggenerated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pp_user
     *
     * @mbggenerated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pp_user
     *
     * @mbggenerated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pp_user
     *
     * @mbggenerated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pp_user
     *
     * @mbggenerated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pp_user
     *
     * @mbggenerated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pp_user
     *
     * @mbggenerated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pp_user
     *
     * @mbggenerated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table pp_user
     *
     * @mbggenerated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andUserPidIsNull() {
            addCriterion("user_pid is null");
            return (Criteria) this;
        }

        public Criteria andUserPidIsNotNull() {
            addCriterion("user_pid is not null");
            return (Criteria) this;
        }

        public Criteria andUserPidEqualTo(Integer value) {
            addCriterion("user_pid =", value, "userPid");
            return (Criteria) this;
        }

        public Criteria andUserPidNotEqualTo(Integer value) {
            addCriterion("user_pid <>", value, "userPid");
            return (Criteria) this;
        }

        public Criteria andUserPidGreaterThan(Integer value) {
            addCriterion("user_pid >", value, "userPid");
            return (Criteria) this;
        }

        public Criteria andUserPidGreaterThanOrEqualTo(Integer value) {
            addCriterion("user_pid >=", value, "userPid");
            return (Criteria) this;
        }

        public Criteria andUserPidLessThan(Integer value) {
            addCriterion("user_pid <", value, "userPid");
            return (Criteria) this;
        }

        public Criteria andUserPidLessThanOrEqualTo(Integer value) {
            addCriterion("user_pid <=", value, "userPid");
            return (Criteria) this;
        }

        public Criteria andUserPidIn(List<Integer> values) {
            addCriterion("user_pid in", values, "userPid");
            return (Criteria) this;
        }

        public Criteria andUserPidNotIn(List<Integer> values) {
            addCriterion("user_pid not in", values, "userPid");
            return (Criteria) this;
        }

        public Criteria andUserPidBetween(Integer value1, Integer value2) {
            addCriterion("user_pid between", value1, value2, "userPid");
            return (Criteria) this;
        }

        public Criteria andUserPidNotBetween(Integer value1, Integer value2) {
            addCriterion("user_pid not between", value1, value2, "userPid");
            return (Criteria) this;
        }

        public Criteria andUserRealnameIsNull() {
            addCriterion("user_realname is null");
            return (Criteria) this;
        }

        public Criteria andUserRealnameIsNotNull() {
            addCriterion("user_realname is not null");
            return (Criteria) this;
        }

        public Criteria andUserRealnameEqualTo(String value) {
            addCriterion("user_realname =", value, "userRealname");
            return (Criteria) this;
        }

        public Criteria andUserRealnameNotEqualTo(String value) {
            addCriterion("user_realname <>", value, "userRealname");
            return (Criteria) this;
        }

        public Criteria andUserRealnameGreaterThan(String value) {
            addCriterion("user_realname >", value, "userRealname");
            return (Criteria) this;
        }

        public Criteria andUserRealnameGreaterThanOrEqualTo(String value) {
            addCriterion("user_realname >=", value, "userRealname");
            return (Criteria) this;
        }

        public Criteria andUserRealnameLessThan(String value) {
            addCriterion("user_realname <", value, "userRealname");
            return (Criteria) this;
        }

        public Criteria andUserRealnameLessThanOrEqualTo(String value) {
            addCriterion("user_realname <=", value, "userRealname");
            return (Criteria) this;
        }

        public Criteria andUserRealnameLike(String value) {
            addCriterion("user_realname like", value, "userRealname");
            return (Criteria) this;
        }

        public Criteria andUserRealnameNotLike(String value) {
            addCriterion("user_realname not like", value, "userRealname");
            return (Criteria) this;
        }

        public Criteria andUserRealnameIn(List<String> values) {
            addCriterion("user_realname in", values, "userRealname");
            return (Criteria) this;
        }

        public Criteria andUserRealnameNotIn(List<String> values) {
            addCriterion("user_realname not in", values, "userRealname");
            return (Criteria) this;
        }

        public Criteria andUserRealnameBetween(String value1, String value2) {
            addCriterion("user_realname between", value1, value2, "userRealname");
            return (Criteria) this;
        }

        public Criteria andUserRealnameNotBetween(String value1, String value2) {
            addCriterion("user_realname not between", value1, value2, "userRealname");
            return (Criteria) this;
        }

        public Criteria andUserIdcardnumIsNull() {
            addCriterion("user_idcardnum is null");
            return (Criteria) this;
        }

        public Criteria andUserIdcardnumIsNotNull() {
            addCriterion("user_idcardnum is not null");
            return (Criteria) this;
        }

        public Criteria andUserIdcardnumEqualTo(String value) {
            addCriterion("user_idcardnum =", value, "userIdcardnum");
            return (Criteria) this;
        }

        public Criteria andUserIdcardnumNotEqualTo(String value) {
            addCriterion("user_idcardnum <>", value, "userIdcardnum");
            return (Criteria) this;
        }

        public Criteria andUserIdcardnumGreaterThan(String value) {
            addCriterion("user_idcardnum >", value, "userIdcardnum");
            return (Criteria) this;
        }

        public Criteria andUserIdcardnumGreaterThanOrEqualTo(String value) {
            addCriterion("user_idcardnum >=", value, "userIdcardnum");
            return (Criteria) this;
        }

        public Criteria andUserIdcardnumLessThan(String value) {
            addCriterion("user_idcardnum <", value, "userIdcardnum");
            return (Criteria) this;
        }

        public Criteria andUserIdcardnumLessThanOrEqualTo(String value) {
            addCriterion("user_idcardnum <=", value, "userIdcardnum");
            return (Criteria) this;
        }

        public Criteria andUserIdcardnumLike(String value) {
            addCriterion("user_idcardnum like", value, "userIdcardnum");
            return (Criteria) this;
        }

        public Criteria andUserIdcardnumNotLike(String value) {
            addCriterion("user_idcardnum not like", value, "userIdcardnum");
            return (Criteria) this;
        }

        public Criteria andUserIdcardnumIn(List<String> values) {
            addCriterion("user_idcardnum in", values, "userIdcardnum");
            return (Criteria) this;
        }

        public Criteria andUserIdcardnumNotIn(List<String> values) {
            addCriterion("user_idcardnum not in", values, "userIdcardnum");
            return (Criteria) this;
        }

        public Criteria andUserIdcardnumBetween(String value1, String value2) {
            addCriterion("user_idcardnum between", value1, value2, "userIdcardnum");
            return (Criteria) this;
        }

        public Criteria andUserIdcardnumNotBetween(String value1, String value2) {
            addCriterion("user_idcardnum not between", value1, value2, "userIdcardnum");
            return (Criteria) this;
        }

        public Criteria andUserAddressIsNull() {
            addCriterion("user_address is null");
            return (Criteria) this;
        }

        public Criteria andUserAddressIsNotNull() {
            addCriterion("user_address is not null");
            return (Criteria) this;
        }

        public Criteria andUserAddressEqualTo(String value) {
            addCriterion("user_address =", value, "userAddress");
            return (Criteria) this;
        }

        public Criteria andUserAddressNotEqualTo(String value) {
            addCriterion("user_address <>", value, "userAddress");
            return (Criteria) this;
        }

        public Criteria andUserAddressGreaterThan(String value) {
            addCriterion("user_address >", value, "userAddress");
            return (Criteria) this;
        }

        public Criteria andUserAddressGreaterThanOrEqualTo(String value) {
            addCriterion("user_address >=", value, "userAddress");
            return (Criteria) this;
        }

        public Criteria andUserAddressLessThan(String value) {
            addCriterion("user_address <", value, "userAddress");
            return (Criteria) this;
        }

        public Criteria andUserAddressLessThanOrEqualTo(String value) {
            addCriterion("user_address <=", value, "userAddress");
            return (Criteria) this;
        }

        public Criteria andUserAddressLike(String value) {
            addCriterion("user_address like", value, "userAddress");
            return (Criteria) this;
        }

        public Criteria andUserAddressNotLike(String value) {
            addCriterion("user_address not like", value, "userAddress");
            return (Criteria) this;
        }

        public Criteria andUserAddressIn(List<String> values) {
            addCriterion("user_address in", values, "userAddress");
            return (Criteria) this;
        }

        public Criteria andUserAddressNotIn(List<String> values) {
            addCriterion("user_address not in", values, "userAddress");
            return (Criteria) this;
        }

        public Criteria andUserAddressBetween(String value1, String value2) {
            addCriterion("user_address between", value1, value2, "userAddress");
            return (Criteria) this;
        }

        public Criteria andUserAddressNotBetween(String value1, String value2) {
            addCriterion("user_address not between", value1, value2, "userAddress");
            return (Criteria) this;
        }

        public Criteria andUserBirthIsNull() {
            addCriterion("user_birth is null");
            return (Criteria) this;
        }

        public Criteria andUserBirthIsNotNull() {
            addCriterion("user_birth is not null");
            return (Criteria) this;
        }

        public Criteria andUserBirthEqualTo(String value) {
            addCriterion("user_birth =", value, "userBirth");
            return (Criteria) this;
        }

        public Criteria andUserBirthNotEqualTo(String value) {
            addCriterion("user_birth <>", value, "userBirth");
            return (Criteria) this;
        }

        public Criteria andUserBirthGreaterThan(String value) {
            addCriterion("user_birth >", value, "userBirth");
            return (Criteria) this;
        }

        public Criteria andUserBirthGreaterThanOrEqualTo(String value) {
            addCriterion("user_birth >=", value, "userBirth");
            return (Criteria) this;
        }

        public Criteria andUserBirthLessThan(String value) {
            addCriterion("user_birth <", value, "userBirth");
            return (Criteria) this;
        }

        public Criteria andUserBirthLessThanOrEqualTo(String value) {
            addCriterion("user_birth <=", value, "userBirth");
            return (Criteria) this;
        }

        public Criteria andUserBirthLike(String value) {
            addCriterion("user_birth like", value, "userBirth");
            return (Criteria) this;
        }

        public Criteria andUserBirthNotLike(String value) {
            addCriterion("user_birth not like", value, "userBirth");
            return (Criteria) this;
        }

        public Criteria andUserBirthIn(List<String> values) {
            addCriterion("user_birth in", values, "userBirth");
            return (Criteria) this;
        }

        public Criteria andUserBirthNotIn(List<String> values) {
            addCriterion("user_birth not in", values, "userBirth");
            return (Criteria) this;
        }

        public Criteria andUserBirthBetween(String value1, String value2) {
            addCriterion("user_birth between", value1, value2, "userBirth");
            return (Criteria) this;
        }

        public Criteria andUserBirthNotBetween(String value1, String value2) {
            addCriterion("user_birth not between", value1, value2, "userBirth");
            return (Criteria) this;
        }

        public Criteria andUserIncomeIsNull() {
            addCriterion("user_income is null");
            return (Criteria) this;
        }

        public Criteria andUserIncomeIsNotNull() {
            addCriterion("user_income is not null");
            return (Criteria) this;
        }

        public Criteria andUserIncomeEqualTo(Integer value) {
            addCriterion("user_income =", value, "userIncome");
            return (Criteria) this;
        }

        public Criteria andUserIncomeNotEqualTo(Integer value) {
            addCriterion("user_income <>", value, "userIncome");
            return (Criteria) this;
        }

        public Criteria andUserIncomeGreaterThan(Integer value) {
            addCriterion("user_income >", value, "userIncome");
            return (Criteria) this;
        }

        public Criteria andUserIncomeGreaterThanOrEqualTo(Integer value) {
            addCriterion("user_income >=", value, "userIncome");
            return (Criteria) this;
        }

        public Criteria andUserIncomeLessThan(Integer value) {
            addCriterion("user_income <", value, "userIncome");
            return (Criteria) this;
        }

        public Criteria andUserIncomeLessThanOrEqualTo(Integer value) {
            addCriterion("user_income <=", value, "userIncome");
            return (Criteria) this;
        }

        public Criteria andUserIncomeIn(List<Integer> values) {
            addCriterion("user_income in", values, "userIncome");
            return (Criteria) this;
        }

        public Criteria andUserIncomeNotIn(List<Integer> values) {
            addCriterion("user_income not in", values, "userIncome");
            return (Criteria) this;
        }

        public Criteria andUserIncomeBetween(Integer value1, Integer value2) {
            addCriterion("user_income between", value1, value2, "userIncome");
            return (Criteria) this;
        }

        public Criteria andUserIncomeNotBetween(Integer value1, Integer value2) {
            addCriterion("user_income not between", value1, value2, "userIncome");
            return (Criteria) this;
        }

        public Criteria andUserProfessionIsNull() {
            addCriterion("user_profession is null");
            return (Criteria) this;
        }

        public Criteria andUserProfessionIsNotNull() {
            addCriterion("user_profession is not null");
            return (Criteria) this;
        }

        public Criteria andUserProfessionEqualTo(Integer value) {
            addCriterion("user_profession =", value, "userProfession");
            return (Criteria) this;
        }

        public Criteria andUserProfessionNotEqualTo(Integer value) {
            addCriterion("user_profession <>", value, "userProfession");
            return (Criteria) this;
        }

        public Criteria andUserProfessionGreaterThan(Integer value) {
            addCriterion("user_profession >", value, "userProfession");
            return (Criteria) this;
        }

        public Criteria andUserProfessionGreaterThanOrEqualTo(Integer value) {
            addCriterion("user_profession >=", value, "userProfession");
            return (Criteria) this;
        }

        public Criteria andUserProfessionLessThan(Integer value) {
            addCriterion("user_profession <", value, "userProfession");
            return (Criteria) this;
        }

        public Criteria andUserProfessionLessThanOrEqualTo(Integer value) {
            addCriterion("user_profession <=", value, "userProfession");
            return (Criteria) this;
        }

        public Criteria andUserProfessionIn(List<Integer> values) {
            addCriterion("user_profession in", values, "userProfession");
            return (Criteria) this;
        }

        public Criteria andUserProfessionNotIn(List<Integer> values) {
            addCriterion("user_profession not in", values, "userProfession");
            return (Criteria) this;
        }

        public Criteria andUserProfessionBetween(Integer value1, Integer value2) {
            addCriterion("user_profession between", value1, value2, "userProfession");
            return (Criteria) this;
        }

        public Criteria andUserProfessionNotBetween(Integer value1, Integer value2) {
            addCriterion("user_profession not between", value1, value2, "userProfession");
            return (Criteria) this;
        }

        public Criteria andUserSexIsNull() {
            addCriterion("user_sex is null");
            return (Criteria) this;
        }

        public Criteria andUserSexIsNotNull() {
            addCriterion("user_sex is not null");
            return (Criteria) this;
        }

        public Criteria andUserSexEqualTo(Integer value) {
            addCriterion("user_sex =", value, "userSex");
            return (Criteria) this;
        }

        public Criteria andUserSexNotEqualTo(Integer value) {
            addCriterion("user_sex <>", value, "userSex");
            return (Criteria) this;
        }

        public Criteria andUserSexGreaterThan(Integer value) {
            addCriterion("user_sex >", value, "userSex");
            return (Criteria) this;
        }

        public Criteria andUserSexGreaterThanOrEqualTo(Integer value) {
            addCriterion("user_sex >=", value, "userSex");
            return (Criteria) this;
        }

        public Criteria andUserSexLessThan(Integer value) {
            addCriterion("user_sex <", value, "userSex");
            return (Criteria) this;
        }

        public Criteria andUserSexLessThanOrEqualTo(Integer value) {
            addCriterion("user_sex <=", value, "userSex");
            return (Criteria) this;
        }

        public Criteria andUserSexIn(List<Integer> values) {
            addCriterion("user_sex in", values, "userSex");
            return (Criteria) this;
        }

        public Criteria andUserSexNotIn(List<Integer> values) {
            addCriterion("user_sex not in", values, "userSex");
            return (Criteria) this;
        }

        public Criteria andUserSexBetween(Integer value1, Integer value2) {
            addCriterion("user_sex between", value1, value2, "userSex");
            return (Criteria) this;
        }

        public Criteria andUserSexNotBetween(Integer value1, Integer value2) {
            addCriterion("user_sex not between", value1, value2, "userSex");
            return (Criteria) this;
        }

        public Criteria andUserEduIsNull() {
            addCriterion("user_edu is null");
            return (Criteria) this;
        }

        public Criteria andUserEduIsNotNull() {
            addCriterion("user_edu is not null");
            return (Criteria) this;
        }

        public Criteria andUserEduEqualTo(Integer value) {
            addCriterion("user_edu =", value, "userEdu");
            return (Criteria) this;
        }

        public Criteria andUserEduNotEqualTo(Integer value) {
            addCriterion("user_edu <>", value, "userEdu");
            return (Criteria) this;
        }

        public Criteria andUserEduGreaterThan(Integer value) {
            addCriterion("user_edu >", value, "userEdu");
            return (Criteria) this;
        }

        public Criteria andUserEduGreaterThanOrEqualTo(Integer value) {
            addCriterion("user_edu >=", value, "userEdu");
            return (Criteria) this;
        }

        public Criteria andUserEduLessThan(Integer value) {
            addCriterion("user_edu <", value, "userEdu");
            return (Criteria) this;
        }

        public Criteria andUserEduLessThanOrEqualTo(Integer value) {
            addCriterion("user_edu <=", value, "userEdu");
            return (Criteria) this;
        }

        public Criteria andUserEduIn(List<Integer> values) {
            addCriterion("user_edu in", values, "userEdu");
            return (Criteria) this;
        }

        public Criteria andUserEduNotIn(List<Integer> values) {
            addCriterion("user_edu not in", values, "userEdu");
            return (Criteria) this;
        }

        public Criteria andUserEduBetween(Integer value1, Integer value2) {
            addCriterion("user_edu between", value1, value2, "userEdu");
            return (Criteria) this;
        }

        public Criteria andUserEduNotBetween(Integer value1, Integer value2) {
            addCriterion("user_edu not between", value1, value2, "userEdu");
            return (Criteria) this;
        }

        public Criteria andUserBalanceIsNull() {
            addCriterion("user_balance is null");
            return (Criteria) this;
        }

        public Criteria andUserBalanceIsNotNull() {
            addCriterion("user_balance is not null");
            return (Criteria) this;
        }

        public Criteria andUserBalanceEqualTo(Integer value) {
            addCriterion("user_balance =", value, "userBalance");
            return (Criteria) this;
        }

        public Criteria andUserBalanceNotEqualTo(Integer value) {
            addCriterion("user_balance <>", value, "userBalance");
            return (Criteria) this;
        }

        public Criteria andUserBalanceGreaterThan(Integer value) {
            addCriterion("user_balance >", value, "userBalance");
            return (Criteria) this;
        }

        public Criteria andUserBalanceGreaterThanOrEqualTo(Integer value) {
            addCriterion("user_balance >=", value, "userBalance");
            return (Criteria) this;
        }

        public Criteria andUserBalanceLessThan(Integer value) {
            addCriterion("user_balance <", value, "userBalance");
            return (Criteria) this;
        }

        public Criteria andUserBalanceLessThanOrEqualTo(Integer value) {
            addCriterion("user_balance <=", value, "userBalance");
            return (Criteria) this;
        }

        public Criteria andUserBalanceIn(List<Integer> values) {
            addCriterion("user_balance in", values, "userBalance");
            return (Criteria) this;
        }

        public Criteria andUserBalanceNotIn(List<Integer> values) {
            addCriterion("user_balance not in", values, "userBalance");
            return (Criteria) this;
        }

        public Criteria andUserBalanceBetween(Integer value1, Integer value2) {
            addCriterion("user_balance between", value1, value2, "userBalance");
            return (Criteria) this;
        }

        public Criteria andUserBalanceNotBetween(Integer value1, Integer value2) {
            addCriterion("user_balance not between", value1, value2, "userBalance");
            return (Criteria) this;
        }

        public Criteria andUserTimeIsNull() {
            addCriterion("user_time is null");
            return (Criteria) this;
        }

        public Criteria andUserTimeIsNotNull() {
            addCriterion("user_time is not null");
            return (Criteria) this;
        }

        public Criteria andUserTimeEqualTo(Integer value) {
            addCriterion("user_time =", value, "userTime");
            return (Criteria) this;
        }

        public Criteria andUserTimeNotEqualTo(Integer value) {
            addCriterion("user_time <>", value, "userTime");
            return (Criteria) this;
        }

        public Criteria andUserTimeGreaterThan(Integer value) {
            addCriterion("user_time >", value, "userTime");
            return (Criteria) this;
        }

        public Criteria andUserTimeGreaterThanOrEqualTo(Integer value) {
            addCriterion("user_time >=", value, "userTime");
            return (Criteria) this;
        }

        public Criteria andUserTimeLessThan(Integer value) {
            addCriterion("user_time <", value, "userTime");
            return (Criteria) this;
        }

        public Criteria andUserTimeLessThanOrEqualTo(Integer value) {
            addCriterion("user_time <=", value, "userTime");
            return (Criteria) this;
        }

        public Criteria andUserTimeIn(List<Integer> values) {
            addCriterion("user_time in", values, "userTime");
            return (Criteria) this;
        }

        public Criteria andUserTimeNotIn(List<Integer> values) {
            addCriterion("user_time not in", values, "userTime");
            return (Criteria) this;
        }

        public Criteria andUserTimeBetween(Integer value1, Integer value2) {
            addCriterion("user_time between", value1, value2, "userTime");
            return (Criteria) this;
        }

        public Criteria andUserTimeNotBetween(Integer value1, Integer value2) {
            addCriterion("user_time not between", value1, value2, "userTime");
            return (Criteria) this;
        }

        public Criteria andUserLasttimeIsNull() {
            addCriterion("user_lasttime is null");
            return (Criteria) this;
        }

        public Criteria andUserLasttimeIsNotNull() {
            addCriterion("user_lasttime is not null");
            return (Criteria) this;
        }

        public Criteria andUserLasttimeEqualTo(Integer value) {
            addCriterion("user_lasttime =", value, "userLasttime");
            return (Criteria) this;
        }

        public Criteria andUserLasttimeNotEqualTo(Integer value) {
            addCriterion("user_lasttime <>", value, "userLasttime");
            return (Criteria) this;
        }

        public Criteria andUserLasttimeGreaterThan(Integer value) {
            addCriterion("user_lasttime >", value, "userLasttime");
            return (Criteria) this;
        }

        public Criteria andUserLasttimeGreaterThanOrEqualTo(Integer value) {
            addCriterion("user_lasttime >=", value, "userLasttime");
            return (Criteria) this;
        }

        public Criteria andUserLasttimeLessThan(Integer value) {
            addCriterion("user_lasttime <", value, "userLasttime");
            return (Criteria) this;
        }

        public Criteria andUserLasttimeLessThanOrEqualTo(Integer value) {
            addCriterion("user_lasttime <=", value, "userLasttime");
            return (Criteria) this;
        }

        public Criteria andUserLasttimeIn(List<Integer> values) {
            addCriterion("user_lasttime in", values, "userLasttime");
            return (Criteria) this;
        }

        public Criteria andUserLasttimeNotIn(List<Integer> values) {
            addCriterion("user_lasttime not in", values, "userLasttime");
            return (Criteria) this;
        }

        public Criteria andUserLasttimeBetween(Integer value1, Integer value2) {
            addCriterion("user_lasttime between", value1, value2, "userLasttime");
            return (Criteria) this;
        }

        public Criteria andUserLasttimeNotBetween(Integer value1, Integer value2) {
            addCriterion("user_lasttime not between", value1, value2, "userLasttime");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table pp_user
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table pp_user
     *
     * @mbggenerated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}