endpoints.shutdown.enabled: true
endpoints.shutdown.sensitive: false

eureka:
  client:
    serviceUrl:
      defaultZone: http://192.168.0.138:8761/eureka/
server:
  port: 8765
spring:
  application:
    name: service-feign