endpoints.shutdown.enabled: true
endpoints.shutdown.sensitive: false

logging.level.root: ERROR
logging.level.org.springframework: INFO
logging.level.com.eason: ERROR

eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:8761/eureka/
server:
  port: 8765
spring:
  application:
    name: service-feign
  http:
    encoding:
      charset: UTF-8
      force: true
      enabled: true
    multipart:
      max-file-size: 20Mb
      max-request-size: 20Mb

# REDIS (RedisProperties)
# Redis数据库索引（默认为0）
spring.redis.database:  0
# Redis服务器地址
spring.redis.host:  45.61.238.68
# Redis服务器连接端口
spring.redis.port:  6378
# Redis服务器连接密码（默认为空）
spring.redis.password:  778092c2cd71661098ff920af0feb89a
# 连接池最大连接数（使用负值表示没有限制）
spring.redis.pool.max-active: -1
# 连接池最大阻塞等待时间（使用负值表示没有限制）
spring.redis.pool.max-wait: -1
# 连接池中的最大空闲连接
spring.redis.pool.max-idle: 8
# 连接池中的最小空闲连接
spring.redis.pool.min-idle: 0
# 连接超时时间（毫秒）
spring.redis.timeout: 0
#TestOnBorrow设置为false，导致有时获取的连接不可用
spring.redis.testOnBorrow:  false

hystrix.command.default.execution.isolation.thread.timeoutInMilliseconds: 60000
ribbon:
  ConnectTimeout: 60000
  ReadTimeout: 60000